'use strict';

const VERSION='5.0.0';
const KEY='pafro_gestao_v5';
const fmtBRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const fmtNum=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);
const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const n=v=>{ if(typeof v==='number') return Number.isFinite(v)?v:0; const s=String(v??'').trim().replace(/\s/g,'').replace(/R\$/gi,'').replace(/\./g,'').replace(',','.'); const x=parseFloat(s); return Number.isFinite(x)?x:0; };
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>fmtBRL.format(n(v));
const pct=v=>`${fmtNum.format(n(v))}%`;
const normalize=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ');

function defaultDB(){return {
  meta:{version:VERSION,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),migratedV3:false},
  config:{
    businessName:'Papel Afro', reservePct:30, wastePct:5, targetMarginRetail:30, targetMarginWholesale:20,
    wholesaleMin:10, monthlyFixed:0, expectedUnitsMonth:100, ownerMonthlyPay:0, ownerHoursMonth:80,
    taxPct:0, commercialEndings:[.50,.60,.80,.90], defaultPayment:'pay_pix',
    notes:'A Reserva PAfro é separada do lucro e pode permanecer no negócio para formar capital e absorver custos ainda não medidos.'
  },
  payments:[
    {id:'pay_pix',name:'Pix — Crescimento',pct:1,fixed:0,active:true,note:'Taxa informada para o plano Crescimento. Revise se sua condição mudar.'},
    {id:'pay_card',name:'Cartão online — base Crescimento',pct:4.59,fixed:.50,active:true,note:'Taxa inicial (“a partir de”). Edite conforme parcelas/condição real.'},
    {id:'pay_boleto',name:'Boleto — Crescimento',pct:0,fixed:2.39,active:true,note:'Tarifa fixa por transação.'},
    {id:'pay_cash',name:'Dinheiro / transferência sem taxa',pct:0,fixed:0,active:true,note:''}
  ],
  suppliers:[], inputs:[], stockMoves:[], products:[], priceHistory:[], orders:[], finance:[], equipment:[]
};}

function loadDB(){
  let db; try{db=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}
  if(!db) db=defaultDB();
  db={...defaultDB(),...db,config:{...defaultDB().config,...(db.config||{})}};
  ['payments','suppliers','inputs','stockMoves','products','priceHistory','orders','finance','equipment'].forEach(k=>db[k]=Array.isArray(db[k])?db[k]:[]);
  // Migração não destrutiva da v3
  if(!db.meta?.migratedV3){
    try{
      const old=JSON.parse(localStorage.getItem('pafro_v2')||'null');
      if(old){
        const supMap={};
        (old.fornecedores||[]).forEach(s=>{ const id=uid('sup'); supMap[s.id]=id; db.suppliers.push({id,name:s.nome||'Fornecedor',contact:s.contato||'',link:s.link||'',note:s.obs||'',createdAt:new Date().toISOString()}); });
        (old.insumos||[]).forEach(i=>db.inputs.push({id:uid('ins'),name:i.nome||'Insumo',unit:'un',referenceCost:n(i.custo),stock:0,minStock:0,supplierId:supMap[i.fornecedorId]||'',note:'Migrado do PAfro Precifica v3',priceHistory:(i.precos||[]).map(p=>({date:p.data||today(),value:n(p.valor),supplierName:p.fornecedorNome||''})),createdAt:new Date().toISOString()}));
      }
    }catch(e){}
    db.meta={...(db.meta||{}),migratedV3:true,version:VERSION}; saveDB(db);
  }
  return db;
}
let DB=loadDB();
function saveDB(db=DB){db.meta=db.meta||{};db.meta.updatedAt=new Date().toISOString();db.meta.version=VERSION;localStorage.setItem(KEY,JSON.stringify(db));}

const nav=[
  ['dashboard','▦','Painel'],['pricing','◈','Precificação'],['products','▣','Produtos'],['inputs','◆','Insumos'],['suppliers','♙','Fornecedores'],
  ['stock','▤','Estoque'],['orders','▧','Orçamentos & Pedidos'],['finance','▥','Financeiro'],['reports','▥','Relatórios'],['settings','⚙','Configurações']
];
let state={view:'dashboard',tab:'calculator',pricing:null,radarMin:1};

function renderNav(){document.querySelector('#mainNav').innerHTML=nav.map(([id,ic,label])=>`<button class="nav-btn ${state.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${ic}</span>${label}</button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.tab=state.view==='pricing'?'calculator':state.tab;closeSidebar();render();});}
function pageHead(title,sub='',actions=''){return `<div class="page-head"><div class="page-title"><h1>${title}</h1><p>${sub}</p></div><div class="page-actions">${actions}</div></div>`}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(html){const m=document.querySelector('#modal');document.querySelector('#modalCard').innerHTML=html;m.classList.remove('hide');m.setAttribute('aria-hidden','false');}
function closeModal(){const m=document.querySelector('#modal');m.classList.add('hide');m.setAttribute('aria-hidden','true');}
function modalShell(title,body,foot=''){return `<div class="modal-head"><h2>${title}</h2><button class="icon-btn" onclick="closeModal()">✕</button></div><div class="modal-body">${body}</div>${foot?`<div class="modal-foot">${foot}</div>`:''}`}
window.closeModal=closeModal;

function paymentById(id){return DB.payments.find(x=>x.id===id)||{id:'none',name:'Sem taxa',pct:0,fixed:0};}
function supplierName(id){return DB.suppliers.find(x=>x.id===id)?.name||'—';}
function inputName(id){return DB.inputs.find(x=>x.id===id)?.name||'—';}
function productById(id){return DB.products.find(x=>x.id===id);}
function inputById(id){return DB.inputs.find(x=>x.id===id);}
function monthKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function dateBR(s){if(!s)return'—';const [y,m,d]=s.slice(0,10).split('-');return `${d}/${m}/${y}`;}
function roundCommercial(x,endings=DB.config.commercialEndings){x=n(x);if(!x)return 0;const base=Math.floor(x);let c=[];for(let b=base-1;b<=base+2;b++)endings.forEach(e=>c.push(b+e));c.push(Math.ceil(x));return c.filter(v=>v>=x-1e-9).sort((a,b)=>a-b)[0]||Math.ceil(x);}
function hourValue(){const c=DB.config;return c.ownerMonthlyPay>0&&c.ownerHoursMonth>0?c.ownerMonthlyPay/c.ownerHoursMonth:0;}
function equipmentMonthly(){return DB.equipment.reduce((s,e)=>{const value=n(e.value),res=n(e.residual),months=Math.max(1,n(e.lifeMonths)||60);return s+Math.max(0,value-res)/months+n(e.maintenanceMonthly);},0);}
function indirectUnit(){const units=Math.max(1,n(DB.config.expectedUnitsMonth));return (n(DB.config.monthlyFixed)+equipmentMonthly())/units;}
function recipeUnitCost(product){return (product?.recipe||[]).reduce((sum,r)=>sum+n(inputById(r.inputId)?.referenceCost)*n(r.qty),0)+n(product?.extraMaterial)+n(product?.packaging)+n(product?.thirdParty);}
function productStockAvailability(product){if(!product?.recipe?.length)return null;let vals=product.recipe.map(r=>{const inp=inputById(r.inputId);const q=n(r.qty);return !inp||q<=0?Infinity:Math.floor(n(inp.stock)/q);});return Math.min(...vals);}

function calculatePrice(opt={}){
  const product=productById(opt.productId);
  const qty=Math.max(1,Math.floor(n(opt.qty)||1));
  const payment=paymentById(opt.paymentId||DB.config.defaultPayment);
  const waste=n(opt.wastePct??product?.wastePct??DB.config.wastePct)/100;
  const reserve=n(opt.reservePct??DB.config.reservePct)/100;
  const margin=n(opt.marginPct??DB.config.targetMarginRetail)/100;
  const tax=n(opt.taxPct??DB.config.taxPct)/100;
  const discount=n(opt.discountPct||0)/100;
  const directUnit=product?recipeUnitCost(product):n(opt.manualDirect);
  const wasteUnit=directUnit*waste;
  const hv=n(opt.hourValue??hourValue());
  const minutesUnit=n(product?.productionMinutes??opt.productionMinutes);
  const setupMinutes=n(product?.setupMinutes??opt.setupMinutes);
  const laborOrder=(minutesUnit*qty+setupMinutes)/60*hv;
  const laborUnit=laborOrder/qty;
  const indUnit=n(opt.indirectUnit??indirectUnit());
  const rawUnit=directUnit+wasteUnit+laborUnit+indUnit;
  const reserveUnit=rawUnit*reserve;
  const protectedUnit=rawUnit+reserveUnit;
  const protectedOrder=protectedUnit*qty;
  const feePct=n(payment.pct)/100;
  const fixed=n(payment.fixed);
  const denomMin=1-feePct-tax;
  const denomTarget=1-feePct-tax-margin;
  if(denomMin<=0||denomTarget<=0)return {error:'A soma de taxas, impostos e margem é alta demais para formar um preço válido.'};
  const minimumOrder=(protectedOrder+fixed)/denomMin;
  const targetChargedOrder=(protectedOrder+fixed)/denomTarget;
  const listOrder=discount<1?targetChargedOrder/(1-discount):targetChargedOrder;
  const minimumUnit=minimumOrder/qty;
  const targetUnit=listOrder/qty;
  const suggestedUnit=roundCommercial(targetUnit);
  const listSuggestedOrder=suggestedUnit*qty;
  const chargedOrder=listSuggestedOrder*(1-discount);
  const fees=chargedOrder*feePct+fixed;
  const taxes=chargedOrder*tax;
  const profit=chargedOrder-fees-taxes-protectedOrder;
  const profitUnit=profit/qty;
  const effectiveMargin=chargedOrder?profit/chargedOrder*100:0;
  return {product,qty,payment,directUnit,wasteUnit,laborUnit,indUnit,rawUnit,reserveUnit,protectedUnit,protectedOrder,minimumOrder,minimumUnit,targetChargedOrder,listOrder,targetUnit,suggestedUnit,listSuggestedOrder,chargedOrder,fees,taxes,profit,profitUnit,effectiveMargin,discount:discount*100,margin:margin*100,waste:waste*100,reserve:reserve*100,hourValue:hv};
}

function render(){renderNav();const v=document.querySelector('#view');const f={dashboard:renderDashboard,pricing:renderPricing,products:renderProducts,inputs:renderInputs,suppliers:renderSuppliers,stock:renderStock,orders:renderOrders,finance:renderFinance,reports:renderReports,settings:renderSettings}[state.view]||renderDashboard;v.innerHTML=f();bindView();}
function bindView(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();});}

function renderDashboard(){
  const mk=monthKey(); const monthOrders=DB.orders.filter(o=>o.date?.startsWith(mk)&&['aprovado','producao','pago','finalizado'].includes(o.status));
  const revenue=monthOrders.reduce((s,o)=>s+n(o.total),0); const profit=monthOrders.reduce((s,o)=>s+n(o.estimatedProfit),0);
  const low=DB.inputs.filter(i=>n(i.minStock)>0&&n(i.stock)<=n(i.minStock)).length;
  const open=DB.orders.filter(o=>!['finalizado','cancelado'].includes(o.status)).length;
  const recent=[...DB.orders].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6);
  return `${pageHead('Painel','Uma visão rápida da operação da Papel Afro.',`<button class="btn yellow" onclick="goPricing()">+ Nova precificação</button>`)}
  <div class="grid cols-4"><div class="card kpi accent-yellow"><div class="label">Faturamento do mês</div><div class="value">${money(revenue)}</div><div class="sub">Pedidos válidos no mês</div></div><div class="card kpi accent-blue"><div class="label">Lucro estimado</div><div class="value">${money(profit)}</div><div class="sub">Após custos, taxas e reserva</div></div><div class="card kpi accent-pink"><div class="label">Pedidos em aberto</div><div class="value">${open}</div><div class="sub">Orçamentos e produção</div></div><div class="card kpi accent-dark"><div class="label">Estoque em atenção</div><div class="value">${low}</div><div class="sub">No mínimo ou abaixo dele</div></div></div>
  <div class="grid cols-2" style="margin-top:14px"><div class="card"><h2>Atalhos</h2><div class="grid cols-2"><button class="btn blue" onclick="go('products');newProduct()">Cadastrar produto</button><button class="btn pink" onclick="go('inputs');newInput()">Cadastrar insumo</button><button class="btn yellow" onclick="go('orders');newOrder()">Novo orçamento</button><button class="btn soft" onclick="go('finance');newFinance()">Lançar financeiro</button></div><div class="notice blue" style="margin-top:14px"><b>Modelo PAfro.</b> O preço parte do custo real, inclui perda, trabalho, custos indiretos, Reserva PAfro e só depois aplica taxas e lucro. Taxa fixa é cobrada uma vez por pedido.</div></div>
  <div class="card"><h2>Pedidos recentes</h2>${recent.length?`<div class="timeline">${recent.map(o=>`<div class="timeline-item"><div class="timeline-date">${dateBR(o.date)}</div><div><div class="timeline-title">${esc(o.customer||'Cliente')} · ${money(o.total)}</div><div class="timeline-sub">${statusLabel(o.status)} · ${(o.items||[]).length} item(ns)</div></div></div>`).join('')}</div>`:`<div class="empty">Nenhum orçamento ou pedido ainda.</div>`}</div></div>`;
}
window.go=v=>{state.view=v;render()};window.goPricing=()=>{state.view='pricing';state.tab='calculator';render()};

function pricingTabs(){return `<div class="tabs"><button class="tab-btn ${state.tab==='calculator'?'active':''}" data-tab="calculator">Calculadora PAfro</button><button class="tab-btn ${state.tab==='volume'?'active':''}" data-tab="volume">Preço por volume</button><button class="tab-btn ${state.tab==='radar'?'active':''}" data-tab="radar">Radar</button><button class="tab-btn ${state.tab==='priceCatalog'?'active':''}" data-tab="priceCatalog">Catálogo de preços</button></div>`}
function renderPricing(){let body='';if(state.tab==='calculator')body=renderCalculator();if(state.tab==='volume')body=renderVolume();if(state.tab==='radar')body=renderRadar();if(state.tab==='priceCatalog')body=renderPriceCatalog();return `${pageHead('Precificação','Custo primeiro. Mercado depois. Lucro e reserva separados.',`<button class="btn outline" onclick="showPricingGuide()">? Como funciona</button>`)}${pricingTabs()}${body}`}
function pricingFormValues(){const p=state.pricing||{};return {productId:p.productId||DB.products[0]?.id||'',qty:p.qty||1,paymentId:p.paymentId||DB.config.defaultPayment,marginPct:p.marginPct??DB.config.targetMarginRetail,reservePct:p.reservePct??DB.config.reservePct,wastePct:p.wastePct??DB.config.wastePct,taxPct:p.taxPct??DB.config.taxPct,discountPct:p.discountPct||0};}
function calcForm(){const x=pricingFormValues();return `<div class="card"><h2>Monte o cenário</h2><div class="form-grid"><label class="field span-6"><span class="label">Produto</span><select id="pcProduct"><option value="">Selecione</option>${DB.products.map(p=>`<option value="${p.id}" ${x.productId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><small>Cadastre a ficha do produto para reaproveitar insumos e tempos.</small></label><label class="field span-3"><span class="label">Quantidade</span><input id="pcQty" inputmode="numeric" value="${x.qty}"></label><label class="field span-3"><span class="label">Pagamento</span><select id="pcPayment">${DB.payments.filter(p=>p.active).map(p=>`<option value="${p.id}" ${x.paymentId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>
  <label class="field span-3"><span class="label">Quanto deve sobrar como lucro (%)</span><input id="pcMargin" inputmode="decimal" value="${x.marginPct}"><small>Percentual real do preço de venda após custos e taxas.</small></label><label class="field span-3"><span class="label">Reserva PAfro (%)</span><input id="pcReserve" inputmode="decimal" value="${x.reservePct}"><small>Separada do lucro; pode formar capital do negócio.</small></label><label class="field span-3"><span class="label">Perda / desperdício (%)</span><input id="pcWaste" inputmode="decimal" value="${x.wastePct}"></label><label class="field span-3"><span class="label">Impostos (%)</span><input id="pcTax" inputmode="decimal" value="${x.taxPct}"></label><label class="field span-3"><span class="label">Desconto previsto (%)</span><input id="pcDiscount" inputmode="decimal" value="${x.discountPct}"><small>O preço de tabela sobe para preservar a conta após o desconto.</small></label></div><div class="form-actions"><button class="btn primary" onclick="runPricing()">Calcular preço</button></div></div>`}
function renderCalculator(){const r=state.pricing?.result;return `<div class="split">${calcForm()}<div>${r?pricingResult(r):`<div class="card"><h2>Resultado</h2><div class="empty">Selecione um produto e calcule. O Precifica mostra o mínimo seguro, o preço sugerido e para onde vai cada real.</div></div>`}</div></div>${r?`<div class="card" style="margin-top:14px"><h2>A conta por unidade</h2>${breakdown(r)}</div>`:''}`}
function readCalcInputs(){return {productId:document.querySelector('#pcProduct')?.value||'',qty:n(document.querySelector('#pcQty')?.value)||1,paymentId:document.querySelector('#pcPayment')?.value,marginPct:n(document.querySelector('#pcMargin')?.value),reservePct:n(document.querySelector('#pcReserve')?.value),wastePct:n(document.querySelector('#pcWaste')?.value),taxPct:n(document.querySelector('#pcTax')?.value),discountPct:n(document.querySelector('#pcDiscount')?.value)};}
window.runPricing=()=>{const opt=readCalcInputs();if(!opt.productId)return toast('Selecione um produto.');const result=calculatePrice(opt);if(result.error)return toast(result.error);state.pricing={...opt,result};render();};
function pricingResult(r){return `<div class="price-hero"><div class="eyebrow">Preço comercial sugerido por unidade</div><div class="price">${money(r.suggestedUnit)}</div><div>${r.qty} un. = <b>${money(r.listSuggestedOrder)}</b>${r.discount?` · cliente paga ${money(r.chargedOrder)} após ${pct(r.discount)} de desconto`:''}</div><div class="price-grid"><div class="price-option"><span>Mínimo seguro</span><b>${money(r.minimumUnit)}</b></div><div class="price-option"><span>Meta calculada</span><b>${money(r.targetUnit)}</b></div><div class="price-option"><span>Lucro estimado</span><b>${money(r.profitUnit)}/un</b></div></div></div><div class="card" style="margin-top:12px"><h3>Leitura rápida</h3><div class="breakdown"><div class="break-row"><span>Custo protegido por unidade</span><b>${money(r.protectedUnit)}</b></div><div class="break-row"><span>Taxa do pagamento no pedido</span><b>${money(r.fees)}</b></div><div class="break-row"><span>Lucro do negócio no pedido</span><b>${money(r.profit)}</b></div><div class="break-row"><span>Margem efetiva</span><b>${pct(r.effectiveMargin)}</b></div></div><div class="form-actions"><button class="btn yellow" onclick="savePriceHistory()">Salvar no histórico</button><button class="btn outline" onclick="saveAsProductPrice()">Definir como preço do produto</button></div></div>`}
function breakdown(r){return `<div class="breakdown"><div class="break-row"><span>Materiais + embalagem + terceiros</span><b>${money(r.directUnit)}</b></div><div class="break-row"><span>Perda (${pct(r.waste)})</span><b>${money(r.wasteUnit)}</b></div><div class="break-row"><span>Seu trabalho</span><b>${money(r.laborUnit)}</b></div><div class="break-row"><span>Custos indiretos + equipamentos</span><b>${money(r.indUnit)}</b></div><div class="break-row"><span>Custo real antes da reserva</span><b>${money(r.rawUnit)}</b></div><div class="break-row"><span>Reserva PAfro (${pct(r.reserve)})</span><b>${money(r.reserveUnit)}</b></div><div class="break-row total"><span>Custo protegido</span><b>${money(r.protectedUnit)}</b></div></div>`}
window.savePriceHistory=()=>{const r=state.pricing?.result;if(!r)return;DB.priceHistory.push({id:uid('price'),date:today(),productId:r.product.id,productName:r.product.name,qty:r.qty,paymentId:r.payment.id,minimumUnit:r.minimumUnit,suggestedUnit:r.suggestedUnit,chargedOrder:r.chargedOrder,profit:r.profit,effectiveMargin:r.effectiveMargin,costSnapshot:r.protectedUnit});saveDB();toast('Precificação salva no histórico.');};
window.saveAsProductPrice=()=>{const r=state.pricing?.result;if(!r)return;const p=productById(r.product.id);p.salePrice=r.suggestedUnit;p.minimumPrice=r.minimumUnit;p.updatedAt=new Date().toISOString();saveDB();toast('Preço definido no produto.');};

function renderVolume(){const p=pricingFormValues();const baseProduct=productById(p.productId);const qs=[1,5,10,20,50,100];let rows='';if(baseProduct){rows=qs.map(q=>{const wholesale=q>=n(DB.config.wholesaleMin);const r=calculatePrice({...p,qty:q,marginPct:wholesale?DB.config.targetMarginWholesale:DB.config.targetMarginRetail});return `<tr><td>${q}</td><td>${wholesale?'<span class="pill blue">Atacado</span>':'<span class="pill">Varejo</span>'}</td><td class="money">${money(r.protectedUnit)}</td><td class="money">${money(r.minimumUnit)}</td><td class="money strong">${money(r.suggestedUnit)}</td><td class="money">${money(r.listSuggestedOrder)}</td><td class="money">${money(r.profit)}</td></tr>`}).join('')}
return `<div class="card"><h2>Preço por volume</h2><div class="form-grid"><label class="field span-6"><span class="label">Produto</span><select id="volProduct" onchange="setVolProduct(this.value)"><option value="">Selecione</option>${DB.products.map(x=>`<option value="${x.id}" ${p.productId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="span-6 notice blue">A tabela recalcula cada quantidade. O tempo de preparação e a taxa fixa de pagamento são diluídos no pedido — não é simplesmente “varejo menos desconto”.</div></div>${baseProduct?`<div class="table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>Qtd.</th><th>Faixa</th><th class="money">Custo protegido/un</th><th class="money">Mínimo/un</th><th class="money">Sugerido/un</th><th class="money">Total</th><th class="money">Lucro pedido</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty">Selecione um produto para gerar as faixas.</div>`}</div>`}
window.setVolProduct=id=>{state.pricing={...(state.pricing||{}),productId:id};render()};

function radarData(){const map={};DB.orders.filter(o=>['aprovado','producao','pago','finalizado'].includes(o.status)).forEach(o=>(o.items||[]).forEach(it=>{const key=normalize(it.name);if(!key)return;(map[key]||(map[key]={name:it.name,prices:[]})).prices.push(n(it.unitPrice));}));return Object.values(map).filter(x=>x.prices.length>=state.radarMin).map(x=>{const a=[...x.prices].sort((a,b)=>a-b);const work=a.length>=5?a.slice(1,-1):a;const avg=work.reduce((s,v)=>s+v,0)/Math.max(1,work.length);const min=Math.min(...a),max=Math.max(...a);return {...x,avg,min,max,osc:avg?((max-min)/avg*100):0,count:a.length};}).sort((a,b)=>b.count-a.count);}
function renderRadar(){const arr=radarData();return `<div class="card"><h2>Radar de preços praticados</h2><p class="muted">Olha para valores realmente usados nos seus pedidos. Com 5 ou mais ocorrências, a referência ignora o menor e o maior valor para reduzir extremos.</p><div class="form-grid"><label class="field span-3"><span class="label">Mínimo de pedidos</span><select onchange="setRadarMin(this.value)">${[1,2,3,5,10].map(v=>`<option ${state.radarMin==v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>Item</th><th>Ocorrências</th><th class="money">Referência</th><th class="money">Faixa</th><th class="money">Oscilação</th></tr></thead><tbody>${arr.length?arr.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.count}</td><td class="money">${money(x.avg)}</td><td class="money">${money(x.min)} – ${money(x.max)}</td><td class="money"><span class="pill ${x.osc>15?'warn':'good'}">${pct(x.osc)}</span></td></tr>`).join(''):`<tr><td colspan="5"><div class="empty">Ainda não há histórico suficiente nos pedidos.</div></td></tr>`}</tbody></table></div></div>`}
window.setRadarMin=v=>{state.radarMin=n(v);render()};
function renderPriceCatalog(){return `<div class="card"><h2>Catálogo de preços decididos</h2><p class="muted">Preço definido por você, com mínimo protegido e custo de referência ao lado.</p><div class="table-wrap"><table class="table"><thead><tr><th>Produto</th><th class="money">Custo protegido*</th><th class="money">Mínimo definido</th><th class="money">Preço de venda</th><th>Atualizado</th><th>Ação</th></tr></thead><tbody>${DB.products.length?DB.products.map(p=>{const r=calculatePrice({productId:p.id,qty:1,paymentId:DB.config.defaultPayment,marginPct:DB.config.targetMarginRetail});return `<tr><td><b>${esc(p.name)}</b></td><td class="money">${money(r.protectedUnit)}</td><td class="money">${p.minimumPrice?money(p.minimumPrice):'—'}</td><td class="money strong">${p.salePrice?money(p.salePrice):'—'}</td><td>${dateBR(p.updatedAt||p.createdAt)}</td><td><button class="btn small outline" onclick="priceProduct('${p.id}')">Precificar</button></td></tr>`}).join(''):`<tr><td colspan="6"><div class="empty">Cadastre produtos para formar seu catálogo.</div></td></tr>`}</tbody></table></div><p class="tiny muted">*Estimativa com as configurações atuais; histórico salvo mantém o snapshot da época.</p></div>`}
window.priceProduct=id=>{state.tab='calculator';state.pricing={productId:id,qty:1,paymentId:DB.config.defaultPayment,marginPct:DB.config.targetMarginRetail,reservePct:DB.config.reservePct,wastePct:DB.config.wastePct,taxPct:DB.config.taxPct,discountPct:0};render()};
window.showPricingGuide=()=>openModal(modalShell('Como o preço é formado',`<div class="notice blue"><b>1. Custo real:</b> insumos + embalagem + terceiros + perda + seu trabalho + custos indiretos/equipamentos.</div><p><b>2. Reserva PAfro:</b> fica separada do lucro e pode permanecer no negócio para formar capital e cobrir custos ainda não medidos.</p><p><b>3. Preço mínimo:</b> cobre o custo protegido, imposto e taxa do meio de pagamento. A tarifa fixa entra uma única vez no pedido.</p><p><b>4. Preço sugerido:</b> acrescenta a margem real desejada sobre o preço de venda e aplica arredondamento comercial sem ficar abaixo da meta.</p><p><b>5. Mercado:</b> serve para posicionamento e comparação; nunca substitui a sua própria conta.</p>`));

function renderProducts(){return `${pageHead('Produtos','Fichas reutilizáveis com receita, tempo de produção e preços.',`<button class="btn yellow" onclick="newProduct()">+ Novo produto</button>`)}<div class="catalog-grid">${DB.products.length?DB.products.map(p=>`<div class="product-card"><div class="product-icon">💡</div><h3>${esc(p.name)}</h3><p>${esc(p.category||'Sem categoria')} · ${n(p.productionMinutes)} min/un</p><div class="price">${p.salePrice?money(p.salePrice):'Sem preço definido'}</div><p>Custo direto atual: ${money(recipeUnitCost(p))} · estoque possível: ${productStockAvailability(p)===null?'—':productStockAvailability(p)}</p><div class="form-actions"><button class="btn small blue" onclick="editProduct('${p.id}')">Editar</button><button class="btn small outline" onclick="priceProductFromCatalog('${p.id}')">Precificar</button><button class="btn small danger" onclick="deleteProduct('${p.id}')">Excluir</button></div></div>`).join(''):`<div class="card"><div class="empty">Nenhum produto cadastrado. Comece criando uma ficha; depois a precificação fica muito mais rápida.</div></div>`}</div>`}
window.priceProductFromCatalog=id=>{state.view='pricing';priceProduct(id)};
function productModal(p={}){const recipe=p.recipe||[];const recipeRows=recipe.length?recipe:[{inputId:'',qty:1}];const body=`<div class="form-grid"><label class="field span-8"><span class="label">Nome do produto</span><input id="prdName" value="${esc(p.name||'')}"></label><label class="field span-4"><span class="label">Categoria</span><input id="prdCat" value="${esc(p.category||'')}"></label><label class="field span-3"><span class="label">Tempo por unidade (min)</span><input id="prdMin" value="${n(p.productionMinutes)}"></label><label class="field span-3"><span class="label">Preparo fixo por pedido (min)</span><input id="prdSetup" value="${n(p.setupMinutes)}"></label><label class="field span-3"><span class="label">Embalagem por un. (R$)</span><input id="prdPack" value="${n(p.packaging)}"></label><label class="field span-3"><span class="label">Outros materiais por un. (R$)</span><input id="prdExtra" value="${n(p.extraMaterial)}"></label><label class="field span-3"><span class="label">Terceiros por un. (R$)</span><input id="prdThird" value="${n(p.thirdParty)}"></label><label class="field span-3"><span class="label">Perda específica (%)</span><input id="prdWaste" placeholder="Padrão ${DB.config.wastePct}%" value="${p.wastePct??''}"></label><label class="field span-3"><span class="label">Preço de venda atual</span><input id="prdPrice" value="${n(p.salePrice)||''}"></label><label class="field span-3"><span class="label">Preço mínimo definido</span><input id="prdMinPrice" value="${n(p.minimumPrice)||''}"></label><div class="span-12"><h3>Receita / insumos por unidade</h3><div id="recipeRows">${recipeRows.map((r,i)=>recipeRow(r,i)).join('')}</div><button class="btn small outline" type="button" onclick="addRecipeRow()">+ Adicionar insumo</button></div><label class="field span-12"><span class="label">Observações</span><textarea id="prdNote">${esc(p.note||'')}</textarea></label></div>`;openModal(modalShell(p.id?'Editar produto':'Novo produto',body,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveProduct('${p.id||''}')">Salvar produto</button>`));}
function recipeRow(r,i){return `<div class="form-grid recipe-row" data-i="${i}" style="margin-bottom:8px"><label class="field span-8"><select class="recipe-input"><option value="">Selecione o insumo</option>${DB.inputs.map(x=>`<option value="${x.id}" ${r.inputId===x.id?'selected':''}>${esc(x.name)} — ${money(x.referenceCost)}/${esc(x.unit)}</option>`).join('')}</select></label><label class="field span-3"><input class="recipe-qty" value="${n(r.qty)||1}" placeholder="Qtd./un"></label><div class="span-1"><button class="btn small danger" type="button" onclick="this.closest('.recipe-row').remove()">×</button></div></div>`}
window.newProduct=()=>productModal({});window.editProduct=id=>productModal(productById(id));window.addRecipeRow=()=>{document.querySelector('#recipeRows').insertAdjacentHTML('beforeend',recipeRow({inputId:'',qty:1},Date.now()));};
window.saveProduct=id=>{const name=document.querySelector('#prdName').value.trim();if(!name)return toast('Informe o nome do produto.');const recipe=[...document.querySelectorAll('.recipe-row')].map(r=>({inputId:r.querySelector('.recipe-input').value,qty:n(r.querySelector('.recipe-qty').value)})).filter(r=>r.inputId&&r.qty>0);const obj={id:id||uid('prd'),name,category:document.querySelector('#prdCat').value.trim(),productionMinutes:n(document.querySelector('#prdMin').value),setupMinutes:n(document.querySelector('#prdSetup').value),packaging:n(document.querySelector('#prdPack').value),extraMaterial:n(document.querySelector('#prdExtra').value),thirdParty:n(document.querySelector('#prdThird').value),wastePct:document.querySelector('#prdWaste').value===''?null:n(document.querySelector('#prdWaste').value),salePrice:n(document.querySelector('#prdPrice').value),minimumPrice:n(document.querySelector('#prdMinPrice').value),recipe,note:document.querySelector('#prdNote').value.trim(),createdAt:productById(id)?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id){DB.products[DB.products.findIndex(x=>x.id===id)]=obj}else DB.products.push(obj);saveDB();closeModal();render();toast('Produto salvo.');};
window.deleteProduct=id=>{if(confirm('Excluir este produto? O histórico de preços será mantido.')){DB.products=DB.products.filter(x=>x.id!==id);saveDB();render();}};

function renderInputs(){return `${pageHead('Insumos','Custo de referência, histórico de preços e estoque em um só cadastro.',`<button class="btn yellow" onclick="newInput()">+ Novo insumo</button>`)}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Insumo</th><th>Fornecedor</th><th>Unidade</th><th class="money">Custo ref.</th><th class="money">Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody>${DB.inputs.length?DB.inputs.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(supplierName(i.supplierId))}</td><td>${esc(i.unit)}</td><td class="money">${money(i.referenceCost)}</td><td class="money">${fmtNum.format(n(i.stock))}</td><td>${n(i.minStock)>0&&n(i.stock)<=n(i.minStock)?'<span class="pill bad">Repor</span>':'<span class="pill good">OK</span>'}</td><td class="actions"><button class="btn small blue" onclick="editInput('${i.id}')">Editar</button> <button class="btn small outline" onclick="registerInputPrice('${i.id}')">Novo preço</button> <button class="btn small danger" onclick="deleteInput('${i.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty">Nenhum insumo cadastrado.</div></td></tr>`}</tbody></table></div></div>`}
function inputModal(i={}){openModal(modalShell(i.id?'Editar insumo':'Novo insumo',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="inName" value="${esc(i.name||'')}"></label><label class="field span-3"><span class="label">Unidade</span><select id="inUnit">${['un','m','cm','kg','g','L','ml','folha','m²'].map(u=>`<option ${i.unit===u?'selected':''}>${u}</option>`).join('')}</select></label><label class="field span-3"><span class="label">Custo de referência (R$)</span><input id="inCost" value="${n(i.referenceCost)||''}"></label><label class="field span-4"><span class="label">Estoque atual</span><input id="inStock" value="${n(i.stock)}"></label><label class="field span-4"><span class="label">Estoque mínimo</span><input id="inMin" value="${n(i.minStock)}"></label><label class="field span-4"><span class="label">Fornecedor principal</span><select id="inSup"><option value="">Sem fornecedor</option>${DB.suppliers.map(s=>`<option value="${s.id}" ${i.supplierId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label class="field span-12"><span class="label">Observação</span><textarea id="inNote">${esc(i.note||'')}</textarea></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveInput('${i.id||''}')">Salvar</button>`));}
window.newInput=()=>inputModal({});window.editInput=id=>inputModal(inputById(id));window.saveInput=id=>{const name=document.querySelector('#inName').value.trim();if(!name)return toast('Informe o nome.');const old=inputById(id);const obj={id:id||uid('ins'),name,unit:document.querySelector('#inUnit').value,referenceCost:n(document.querySelector('#inCost').value),stock:n(document.querySelector('#inStock').value),minStock:n(document.querySelector('#inMin').value),supplierId:document.querySelector('#inSup').value,note:document.querySelector('#inNote').value.trim(),priceHistory:old?.priceHistory||[],createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.inputs[DB.inputs.findIndex(x=>x.id===id)]=obj;else DB.inputs.push(obj);saveDB();closeModal();render();toast('Insumo salvo.');};
window.deleteInput=id=>{if(DB.products.some(p=>(p.recipe||[]).some(r=>r.inputId===id)))return alert('Este insumo está sendo usado em um produto. Remova-o da receita antes de excluir.');if(confirm('Excluir este insumo?')){DB.inputs=DB.inputs.filter(x=>x.id!==id);saveDB();render();}};
window.registerInputPrice=id=>{const i=inputById(id);openModal(modalShell('Registrar preço encontrado',`<div class="form-grid"><label class="field span-4"><span class="label">Preço encontrado</span><input id="rpValue"></label><label class="field span-4"><span class="label">Data</span><input type="date" id="rpDate" value="${today()}"></label><label class="field span-4"><span class="label">Fornecedor</span><select id="rpSup"><option value="">Outro / não informado</option>${DB.suppliers.map(s=>`<option value="${s.id}" ${i.supplierId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label class="field span-12"><span class="label">Observação</span><input id="rpNote"></label><label class="field span-12"><input type="checkbox" id="rpRef" style="width:auto"> <b>Usar este valor como novo custo de referência</b></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveInputPrice('${id}')">Registrar</button>`));};
window.saveInputPrice=id=>{const i=inputById(id),v=n(document.querySelector('#rpValue').value);if(!v)return toast('Informe o preço.');i.priceHistory=i.priceHistory||[];i.priceHistory.push({date:document.querySelector('#rpDate').value||today(),value:v,supplierId:document.querySelector('#rpSup').value,note:document.querySelector('#rpNote').value.trim()});if(document.querySelector('#rpRef').checked)i.referenceCost=v;i.updatedAt=new Date().toISOString();saveDB();closeModal();render();toast('Preço registrado.');};

function renderSuppliers(){return `${pageHead('Fornecedores','Contatos e referências de compra.',`<button class="btn yellow" onclick="newSupplier()">+ Novo fornecedor</button>`)}<div class="grid cols-3">${DB.suppliers.length?DB.suppliers.map(s=>`<div class="card"><h3>${esc(s.name)}</h3><p>${esc(s.contact||'Sem contato')}</p>${s.link?`<p><a href="${esc(s.link)}" target="_blank" rel="noopener">Abrir link</a></p>`:''}<p class="muted">${esc(s.note||'')}</p><div class="form-actions"><button class="btn small blue" onclick="editSupplier('${s.id}')">Editar</button><button class="btn small danger" onclick="deleteSupplier('${s.id}')">Excluir</button></div></div>`).join(''):`<div class="card"><div class="empty">Nenhum fornecedor cadastrado.</div></div>`}</div>`}
function supplierModal(s={}){openModal(modalShell(s.id?'Editar fornecedor':'Novo fornecedor',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="spName" value="${esc(s.name||'')}"></label><label class="field span-6"><span class="label">Contato</span><input id="spContact" value="${esc(s.contact||'')}"></label><label class="field span-12"><span class="label">Link / site</span><input id="spLink" value="${esc(s.link||'')}"></label><label class="field span-12"><span class="label">Observação</span><textarea id="spNote">${esc(s.note||'')}</textarea></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveSupplier('${s.id||''}')">Salvar</button>`));}
window.newSupplier=()=>supplierModal({});window.editSupplier=id=>supplierModal(DB.suppliers.find(x=>x.id===id));window.saveSupplier=id=>{const name=document.querySelector('#spName').value.trim();if(!name)return toast('Informe o nome.');const old=DB.suppliers.find(x=>x.id===id);const o={id:id||uid('sup'),name,contact:document.querySelector('#spContact').value.trim(),link:document.querySelector('#spLink').value.trim(),note:document.querySelector('#spNote').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.suppliers[DB.suppliers.findIndex(x=>x.id===id)]=o;else DB.suppliers.push(o);saveDB();closeModal();render();};window.deleteSupplier=id=>{if(confirm('Excluir fornecedor? Os insumos continuarão cadastrados.')){DB.suppliers=DB.suppliers.filter(x=>x.id!==id);DB.inputs.forEach(i=>{if(i.supplierId===id)i.supplierId=''});saveDB();render();}};

function renderStock(){const moves=[...DB.stockMoves].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,20);return `${pageHead('Estoque','Entradas, saídas e alertas de reposição.',`<button class="btn yellow" onclick="newStockMove()">+ Movimentar estoque</button>`)}<div class="grid cols-2"><div class="card"><h2>Posição atual</h2><div class="table-wrap"><table class="table"><thead><tr><th>Insumo</th><th class="money">Atual</th><th class="money">Mínimo</th><th>Status</th></tr></thead><tbody>${DB.inputs.length?DB.inputs.map(i=>`<tr><td>${esc(i.name)}</td><td class="money">${fmtNum.format(n(i.stock))} ${esc(i.unit)}</td><td class="money">${fmtNum.format(n(i.minStock))}</td><td>${n(i.minStock)>0&&n(i.stock)<=n(i.minStock)?'<span class="pill bad">Repor</span>':'<span class="pill good">OK</span>'}</td></tr>`).join(''):`<tr><td colspan="4"><div class="empty">Cadastre insumos.</div></td></tr>`}</tbody></table></div></div><div class="card"><h2>Movimentações recentes</h2>${moves.length?`<div class="timeline">${moves.map(m=>`<div class="timeline-item"><div class="timeline-date">${dateBR(m.date)}</div><div><div class="timeline-title">${esc(inputName(m.inputId))} · ${m.type==='in'?'+':'−'}${fmtNum.format(n(m.qty))}</div><div class="timeline-sub">${esc(m.reason||'Movimentação')}</div></div></div>`).join('')}</div>`:`<div class="empty">Sem movimentações ainda.</div>`}</div></div>`}
window.newStockMove=()=>openModal(modalShell('Movimentar estoque',`<div class="form-grid"><label class="field span-6"><span class="label">Insumo</span><select id="mvInput">${DB.inputs.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select></label><label class="field span-3"><span class="label">Tipo</span><select id="mvType"><option value="in">Entrada</option><option value="out">Saída</option></select></label><label class="field span-3"><span class="label">Quantidade</span><input id="mvQty"></label><label class="field span-4"><span class="label">Data</span><input type="date" id="mvDate" value="${today()}"></label><label class="field span-8"><span class="label">Motivo</span><input id="mvReason" placeholder="Compra, ajuste, produção..."></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveStockMove()">Registrar</button>`));
window.saveStockMove=()=>{const input=inputById(document.querySelector('#mvInput').value),q=n(document.querySelector('#mvQty').value),type=document.querySelector('#mvType').value;if(!input||q<=0)return toast('Informe insumo e quantidade.');if(type==='out'&&n(input.stock)<q&&!confirm('A saída deixará o estoque negativo. Continuar?'))return;input.stock=n(input.stock)+(type==='in'?q:-q);DB.stockMoves.push({id:uid('mov'),inputId:input.id,type,qty:q,date:document.querySelector('#mvDate').value||today(),reason:document.querySelector('#mvReason').value.trim()});saveDB();closeModal();render();};

function statusLabel(s){return ({orcamento:'Orçamento',aprovado:'Aprovado',producao:'Em produção',pago:'Pago',finalizado:'Finalizado',cancelado:'Cancelado'})[s]||s||'—'}
function renderOrders(){const orders=[...DB.orders].sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `${pageHead('Orçamentos & Pedidos','Registre o que foi orçado, negociado e vendido.',`<button class="btn yellow" onclick="newOrder()">+ Novo orçamento</button>`)}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Cliente</th><th>Status</th><th>Itens</th><th class="money">Total</th><th class="money">Lucro est.</th><th>Ações</th></tr></thead><tbody>${orders.length?orders.map(o=>`<tr><td>${dateBR(o.date)}</td><td><b>${esc(o.customer||'Cliente')}</b></td><td><span class="pill ${o.status==='cancelado'?'bad':o.status==='finalizado'||o.status==='pago'?'good':'blue'}">${statusLabel(o.status)}</span></td><td>${(o.items||[]).map(i=>`${esc(i.name)} × ${i.qty}`).join('<br>')}</td><td class="money strong">${money(o.total)}</td><td class="money">${money(o.estimatedProfit)}</td><td><button class="btn small blue" onclick="editOrder('${o.id}')">Editar</button> <button class="btn small danger" onclick="deleteOrder('${o.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty">Nenhum orçamento ainda.</div></td></tr>`}</tbody></table></div></div>`}
function orderItemRow(it={}){return `<div class="form-grid order-item" style="margin-bottom:8px"><label class="field span-5"><select class="oiProduct" onchange="fillOrderItem(this)"><option value="">Produto / item livre</option>${DB.products.map(p=>`<option value="${p.id}" ${it.productId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><input class="oiName" style="margin-top:5px" placeholder="Nome do item" value="${esc(it.name||'')}"></label><label class="field span-2"><input class="oiQty" placeholder="Qtd." value="${n(it.qty)||1}"></label><label class="field span-2"><input class="oiPrice" placeholder="R$/un" value="${n(it.unitPrice)||''}"></label><label class="field span-2"><input class="oiCost" placeholder="Custo/un" value="${n(it.costUnit)||''}"></label><div class="span-1"><button class="btn small danger" onclick="this.closest('.order-item').remove()">×</button></div></div>`}
function orderModal(o={}){const items=o.items?.length?o.items:[{}];openModal(modalShell(o.id?'Editar pedido':'Novo orçamento',`<div class="form-grid"><label class="field span-4"><span class="label">Cliente</span><input id="odCustomer" value="${esc(o.customer||'')}"></label><label class="field span-3"><span class="label">Data</span><input type="date" id="odDate" value="${o.date||today()}"></label><label class="field span-3"><span class="label">Status</span><select id="odStatus">${['orcamento','aprovado','producao','pago','finalizado','cancelado'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></label><label class="field span-2"><span class="label">Pagamento</span><select id="odPay">${DB.payments.map(p=>`<option value="${p.id}" ${o.paymentId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><div class="span-12"><h3>Itens</h3><div id="orderItems">${items.map(orderItemRow).join('')}</div><button class="btn small outline" onclick="addOrderItem()">+ Item</button></div><label class="field span-12"><span class="label">Observações</span><textarea id="odNote">${esc(o.note||'')}</textarea></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveOrder('${o.id||''}')">Salvar</button>`));}
window.newOrder=()=>orderModal({status:'orcamento',paymentId:DB.config.defaultPayment});window.editOrder=id=>orderModal(DB.orders.find(x=>x.id===id));window.addOrderItem=()=>document.querySelector('#orderItems').insertAdjacentHTML('beforeend',orderItemRow({}));
window.fillOrderItem=el=>{const row=el.closest('.order-item'),p=productById(el.value);if(!p)return;row.querySelector('.oiName').value=p.name;row.querySelector('.oiPrice').value=p.salePrice||'';const r=calculatePrice({productId:p.id,qty:1,paymentId:document.querySelector('#odPay')?.value||DB.config.defaultPayment,marginPct:DB.config.targetMarginRetail});row.querySelector('.oiCost').value=r.protectedUnit.toFixed(2).replace('.',',');};
window.saveOrder=id=>{const items=[...document.querySelectorAll('.order-item')].map(r=>({productId:r.querySelector('.oiProduct').value,name:r.querySelector('.oiName').value.trim(),qty:Math.max(1,n(r.querySelector('.oiQty').value)||1),unitPrice:n(r.querySelector('.oiPrice').value),costUnit:n(r.querySelector('.oiCost').value)})).filter(i=>i.name&&i.unitPrice>=0);if(!items.length)return toast('Inclua pelo menos um item.');const total=items.reduce((s,i)=>s+i.qty*i.unitPrice,0),cost=items.reduce((s,i)=>s+i.qty*i.costUnit,0);const pay=paymentById(document.querySelector('#odPay').value),fees=total*n(pay.pct)/100+n(pay.fixed),taxes=total*n(DB.config.taxPct)/100,profit=total-cost-fees-taxes;const old=DB.orders.find(x=>x.id===id);const status=document.querySelector('#odStatus').value;const obj={id:id||uid('ord'),customer:document.querySelector('#odCustomer').value.trim(),date:document.querySelector('#odDate').value||today(),status,paymentId:pay.id,items,total,cost,estimatedProfit:profit,note:document.querySelector('#odNote').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.orders[DB.orders.findIndex(x=>x.id===id)]=obj;else DB.orders.push(obj);if(status==='pago'&&!DB.finance.some(f=>f.orderId===obj.id)){DB.finance.push({id:uid('fin'),date:obj.date,type:'income',category:'Vendas',description:`Pedido ${obj.customer||obj.id}`,amount:obj.total,orderId:obj.id});}saveDB();closeModal();render();toast('Pedido salvo.');};window.deleteOrder=id=>{if(confirm('Excluir este pedido?')){DB.orders=DB.orders.filter(x=>x.id!==id);saveDB();render();}};

function renderFinance(){const mk=monthKey(),mov=[...DB.finance].sort((a,b)=>String(b.date).localeCompare(String(a.date)));const month=mov.filter(f=>f.date?.startsWith(mk));const inc=month.filter(f=>f.type==='income').reduce((s,f)=>s+n(f.amount),0),exp=month.filter(f=>f.type==='expense').reduce((s,f)=>s+n(f.amount),0);return `${pageHead('Financeiro','Entradas e saídas para acompanhar o caixa real.',`<button class="btn yellow" onclick="newFinance()">+ Novo lançamento</button>`)}<div class="grid cols-3"><div class="card kpi accent-blue"><div class="label">Entradas no mês</div><div class="value">${money(inc)}</div></div><div class="card kpi accent-pink"><div class="label">Saídas no mês</div><div class="value">${money(exp)}</div></div><div class="card kpi accent-yellow"><div class="label">Saldo do mês</div><div class="value">${money(inc-exp)}</div></div></div><div class="card" style="margin-top:14px"><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th class="money">Valor</th><th></th></tr></thead><tbody>${mov.length?mov.map(f=>`<tr><td>${dateBR(f.date)}</td><td><span class="pill ${f.type==='income'?'good':'bad'}">${f.type==='income'?'Entrada':'Saída'}</span></td><td>${esc(f.category||'')}</td><td>${esc(f.description||'')}</td><td class="money">${money(f.amount)}</td><td><button class="btn small danger" onclick="deleteFinance('${f.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">Nenhum lançamento financeiro.</div></td></tr>`}</tbody></table></div></div>`}
window.newFinance=()=>openModal(modalShell('Novo lançamento',`<div class="form-grid"><label class="field span-3"><span class="label">Tipo</span><select id="fnType"><option value="income">Entrada</option><option value="expense">Saída</option></select></label><label class="field span-3"><span class="label">Data</span><input type="date" id="fnDate" value="${today()}"></label><label class="field span-3"><span class="label">Valor</span><input id="fnAmount"></label><label class="field span-3"><span class="label">Categoria</span><input id="fnCat" placeholder="Vendas, insumos..."></label><label class="field span-12"><span class="label">Descrição</span><input id="fnDesc"></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveFinance()">Salvar</button>`));window.saveFinance=()=>{const a=n(document.querySelector('#fnAmount').value);if(a<=0)return toast('Informe o valor.');DB.finance.push({id:uid('fin'),date:document.querySelector('#fnDate').value||today(),type:document.querySelector('#fnType').value,category:document.querySelector('#fnCat').value.trim(),description:document.querySelector('#fnDesc').value.trim(),amount:a});saveDB();closeModal();render();};window.deleteFinance=id=>{if(confirm('Excluir lançamento?')){DB.finance=DB.finance.filter(x=>x.id!==id);saveDB();render();}};

function renderReports(){const valid=DB.orders.filter(o=>['aprovado','producao','pago','finalizado'].includes(o.status));const revenue=valid.reduce((s,o)=>s+n(o.total),0),profit=valid.reduce((s,o)=>s+n(o.estimatedProfit),0);const by={};valid.forEach(o=>(o.items||[]).forEach(i=>{const k=normalize(i.name);by[k]=by[k]||{name:i.name,qty:0,revenue:0,profit:0};by[k].qty+=n(i.qty);by[k].revenue+=n(i.qty)*n(i.unitPrice);by[k].profit+=(n(i.unitPrice)-n(i.costUnit))*n(i.qty);}));const products=Object.values(by).sort((a,b)=>b.revenue-a.revenue);return `${pageHead('Relatórios','Leituras simples para decidir com os dados que a PAfro já gerou.',`<button class="btn outline" onclick="exportCSV()">Exportar CSV de pedidos</button>`)}<div class="grid cols-4"><div class="card kpi accent-blue"><div class="label">Receita registrada</div><div class="value">${money(revenue)}</div></div><div class="card kpi accent-yellow"><div class="label">Lucro estimado</div><div class="value">${money(profit)}</div></div><div class="card kpi accent-pink"><div class="label">Ticket médio</div><div class="value">${money(valid.length?revenue/valid.length:0)}</div></div><div class="card kpi accent-dark"><div class="label">Pedidos válidos</div><div class="value">${valid.length}</div></div></div><div class="card" style="margin-top:14px"><h2>Desempenho por item</h2><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th class="money">Qtd.</th><th class="money">Receita</th><th class="money">Resultado bruto*</th></tr></thead><tbody>${products.length?products.map(x=>`<tr><td>${esc(x.name)}</td><td class="money">${x.qty}</td><td class="money">${money(x.revenue)}</td><td class="money">${money(x.profit)}</td></tr>`).join(''):`<tr><td colspan="4"><div class="empty">Registre pedidos para gerar relatórios.</div></td></tr>`}</tbody></table></div><p class="tiny muted">*Baseado no custo registrado nos itens; taxas do pedido são tratadas no lucro estimado geral.</p></div>`}
window.exportCSV=()=>{const rows=[['Data','Cliente','Status','Item','Quantidade','Preço unitário','Total item']];DB.orders.forEach(o=>(o.items||[]).forEach(i=>rows.push([o.date,o.customer,o.status,i.name,i.qty,i.unitPrice,n(i.qty)*n(i.unitPrice)])));const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),'pafro-pedidos.csv');};

function renderSettings(){return `${pageHead('Configurações','Premissas do negócio, pagamentos, equipamentos e segurança dos dados.')}
<div class="subtabs"><button class="subtab ${state.tab==='business'||!['payments','equipment','backup'].includes(state.tab)?'active':''}" data-tab="business">Negócio</button><button class="subtab ${state.tab==='payments'?'active':''}" data-tab="payments">Pagamentos</button><button class="subtab ${state.tab==='equipment'?'active':''}" data-tab="equipment">Equipamentos</button><button class="subtab ${state.tab==='backup'?'active':''}" data-tab="backup">Backup</button></div>${state.tab==='payments'?settingsPayments():state.tab==='equipment'?settingsEquipment():state.tab==='backup'?settingsBackup():settingsBusiness()}`}
function settingsBusiness(){const c=DB.config;return `<div class="card"><h2>Premissas da Papel Afro</h2><div class="form-grid"><label class="field span-3"><span class="label">Reserva PAfro (%)</span><input id="cfgReserve" value="${c.reservePct}"></label><label class="field span-3"><span class="label">Perda padrão (%)</span><input id="cfgWaste" value="${c.wastePct}"></label><label class="field span-3"><span class="label">Lucro varejo (%)</span><input id="cfgRetail" value="${c.targetMarginRetail}"></label><label class="field span-3"><span class="label">Lucro atacado (%)</span><input id="cfgWholesale" value="${c.targetMarginWholesale}"></label><label class="field span-3"><span class="label">Atacado a partir de</span><input id="cfgWholesaleMin" value="${c.wholesaleMin}"></label><label class="field span-3"><span class="label">Impostos (%)</span><input id="cfgTax" value="${c.taxPct}"></label><label class="field span-3"><span class="label">Custos fixos mensais (R$)</span><input id="cfgFixed" value="${c.monthlyFixed}"></label><label class="field span-3"><span class="label">Produção esperada/mês (un.)</span><input id="cfgUnits" value="${c.expectedUnitsMonth}"></label><label class="field span-3"><span class="label">Quanto quer receber/mês</span><input id="cfgPay" value="${c.ownerMonthlyPay}"></label><label class="field span-3"><span class="label">Horas dedicadas/mês</span><input id="cfgHours" value="${c.ownerHoursMonth}"></label><div class="span-6 notice blue"><b>Valor calculado da sua hora: ${money(hourValue())}</b><br>Custos indiretos/equipamentos por unidade: ${money(indirectUnit())}</div></div><div class="form-actions"><button class="btn primary" onclick="saveBusinessSettings()">Salvar configurações</button></div></div>`}
window.saveBusinessSettings=()=>{Object.assign(DB.config,{reservePct:n(q('#cfgReserve').value),wastePct:n(q('#cfgWaste').value),targetMarginRetail:n(q('#cfgRetail').value),targetMarginWholesale:n(q('#cfgWholesale').value),wholesaleMin:Math.max(1,n(q('#cfgWholesaleMin').value)),taxPct:n(q('#cfgTax').value),monthlyFixed:n(q('#cfgFixed').value),expectedUnitsMonth:Math.max(1,n(q('#cfgUnits').value)),ownerMonthlyPay:n(q('#cfgPay').value),ownerHoursMonth:Math.max(1,n(q('#cfgHours').value))});saveDB();render();toast('Configurações salvas.');};
function q(s){return document.querySelector(s)}
function settingsPayments(){return `<div class="card"><div class="page-head"><div><h2>Meios de pagamento</h2><p class="muted">Percentual sobre a venda + tarifa fixa por transação.</p></div><button class="btn yellow" onclick="newPayment()">+ Adicionar</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th class="money">%</th><th class="money">Fixa</th><th>Observação</th><th>Ações</th></tr></thead><tbody>${DB.payments.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td class="money">${pct(p.pct)}</td><td class="money">${money(p.fixed)}</td><td>${esc(p.note||'')}</td><td><button class="btn small blue" onclick="editPayment('${p.id}')">Editar</button> <button class="btn small danger" onclick="deletePayment('${p.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div></div>`}
function paymentModal(p={}){openModal(modalShell(p.id?'Editar pagamento':'Novo pagamento',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="pmName" value="${esc(p.name||'')}"></label><label class="field span-3"><span class="label">Taxa (%)</span><input id="pmPct" value="${n(p.pct)}"></label><label class="field span-3"><span class="label">Tarifa fixa (R$)</span><input id="pmFixed" value="${n(p.fixed)}"></label><label class="field span-12"><span class="label">Observação</span><input id="pmNote" value="${esc(p.note||'')}"></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="savePayment('${p.id||''}')">Salvar</button>`));}
window.newPayment=()=>paymentModal({});window.editPayment=id=>paymentModal(DB.payments.find(x=>x.id===id));window.savePayment=id=>{const name=q('#pmName').value.trim();if(!name)return toast('Informe o nome.');const old=DB.payments.find(x=>x.id===id);const o={id:id||uid('pay'),name,pct:n(q('#pmPct').value),fixed:n(q('#pmFixed').value),note:q('#pmNote').value.trim(),active:true};if(id)DB.payments[DB.payments.findIndex(x=>x.id===id)]=o;else DB.payments.push(o);saveDB();closeModal();render();};window.deletePayment=id=>{if(DB.payments.length<=1)return toast('Mantenha pelo menos um meio de pagamento.');if(confirm('Excluir este meio de pagamento?')){DB.payments=DB.payments.filter(x=>x.id!==id);if(DB.config.defaultPayment===id)DB.config.defaultPayment=DB.payments[0].id;saveDB();render();}};
function settingsEquipment(){return `<div class="card"><div class="page-head"><div><h2>Equipamentos</h2><p class="muted">Depreciação e manutenção entram nos custos indiretos.</p></div><button class="btn yellow" onclick="newEquipment()">+ Equipamento</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Equipamento</th><th class="money">Valor</th><th>Vida útil</th><th class="money">Deprec./mês</th><th class="money">Manutenção/mês</th><th></th></tr></thead><tbody>${DB.equipment.length?DB.equipment.map(e=>{const dep=Math.max(0,n(e.value)-n(e.residual))/Math.max(1,n(e.lifeMonths));return `<tr><td>${esc(e.name)}</td><td class="money">${money(e.value)}</td><td>${e.lifeMonths} meses</td><td class="money">${money(dep)}</td><td class="money">${money(e.maintenanceMonthly)}</td><td><button class="btn small blue" onclick="editEquipment('${e.id}')">Editar</button> <button class="btn small danger" onclick="deleteEquipment('${e.id}')">Excluir</button></td></tr>`}).join(''):`<tr><td colspan="6"><div class="empty">Você pode cadastrar prensa, impressora e outros equipamentos.</div></td></tr>`}</tbody></table></div></div>`}
function equipmentModal(e={}){openModal(modalShell(e.id?'Editar equipamento':'Novo equipamento',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="eqName" value="${esc(e.name||'')}"></label><label class="field span-3"><span class="label">Valor de compra</span><input id="eqValue" value="${n(e.value)||''}"></label><label class="field span-3"><span class="label">Valor residual</span><input id="eqResidual" value="${n(e.residual)||''}"></label><label class="field span-4"><span class="label">Vida útil (meses)</span><input id="eqLife" value="${n(e.lifeMonths)||60}"></label><label class="field span-4"><span class="label">Manutenção mensal estimada</span><input id="eqMaint" value="${n(e.maintenanceMonthly)||''}"></label><label class="field span-4"><span class="label">Data da compra</span><input type="date" id="eqDate" value="${e.purchaseDate||''}"></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveEquipment('${e.id||''}')">Salvar</button>`));}
window.newEquipment=()=>equipmentModal({});window.editEquipment=id=>equipmentModal(DB.equipment.find(x=>x.id===id));window.saveEquipment=id=>{const name=q('#eqName').value.trim();if(!name)return toast('Informe o nome.');const o={id:id||uid('eq'),name,value:n(q('#eqValue').value),residual:n(q('#eqResidual').value),lifeMonths:Math.max(1,n(q('#eqLife').value)||60),maintenanceMonthly:n(q('#eqMaint').value),purchaseDate:q('#eqDate').value};if(id)DB.equipment[DB.equipment.findIndex(x=>x.id===id)]=o;else DB.equipment.push(o);saveDB();closeModal();render();};window.deleteEquipment=id=>{if(confirm('Excluir equipamento?')){DB.equipment=DB.equipment.filter(x=>x.id!==id);saveDB();render();}};
function settingsBackup(){return `<div class="grid cols-2"><div class="card"><h2>Backup</h2><p>Seus dados ficam neste aparelho/navegador. Exporte uma cópia regularmente, especialmente antes de trocar de celular ou limpar o navegador.</p><div class="form-actions"><button class="btn yellow" onclick="exportBackup()">Exportar backup JSON</button><button class="btn outline" onclick="triggerImport()">Importar backup</button></div></div><div class="card"><h2>Segurança</h2><div class="notice bad"><b>Apagar tudo é irreversível neste aparelho.</b> Exporte um backup antes.</div><div class="form-actions"><button class="btn danger" onclick="resetAll()">Apagar todos os dados</button></div></div></div>`}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);}
window.exportBackup=()=>downloadBlob(new Blob([JSON.stringify(DB,null,2)],{type:'application/json'}),`pafro-gestao-backup-${today()}.json`);window.triggerImport=()=>q('#importFile').click();window.resetAll=()=>{if(confirm('Tem certeza? Isso apaga todos os dados locais da PAfro Gestão neste navegador.')){DB=defaultDB();saveDB();state={view:'dashboard',tab:'calculator',pricing:null,radarMin:1};render();toast('Dados reiniciados.');}};

q('#importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.config)throw new Error();DB={...defaultDB(),...d,config:{...defaultDB().config,...d.config}};saveDB();render();toast('Backup importado.');}catch(err){alert('Arquivo de backup inválido.')}};r.readAsText(f);e.target.value='';});
q('#menuBtn').onclick=()=>q('#sidebar').classList.toggle('open');function closeSidebar(){q('#sidebar').classList.remove('open')}
q('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
