'use strict';
/* PAfro Gestão v5 — consolidação da operação + busca inteligente nos cadastros */

(function(){
  const OLD_KEY='pafro_gestao_v4';
  const V5='5.0.0';

  function ensureSchema(){
    // Migração v4 -> v5 somente se o banco v5 ainda estiver vazio.
    try{
      const old=JSON.parse(localStorage.getItem(OLD_KEY)||'null');
      const current=JSON.parse(localStorage.getItem('pafro_gestao_v5')||'null');
      const empty=!current || !['products','inputs','orders','finance'].some(k=>(current[k]||[]).length);
      if(old && empty){ DB={...old,meta:{...(old.meta||{}),version:V5,migratedV4:true}}; }
    }catch(e){}
    const arrays=['categories','customers','coupons','catalogLinks','businessHours','catalogSales'];
    arrays.forEach(k=>{if(!Array.isArray(DB[k]))DB[k]=[];});
    DB.config={
      ...(DB.config||{}),
      ownerName:DB.config?.ownerName||'', businessPhone:DB.config?.businessPhone||'', businessEmail:DB.config?.businessEmail||'',
      whatsappLink:DB.config?.whatsappLink||'', catalogSlogan:DB.config?.catalogSlogan||'Personalizados com identidade, afeto e criatividade.',
      catalogIntro:DB.config?.catalogIntro||'', catalogColor:DB.config?.catalogColor||'#ffef21', catalogActive:DB.config?.catalogActive??true,
      catalogSlug:DB.config?.catalogSlug||'papel-afro', orderValidityDays:DB.config?.orderValidityDays||7,
      deliveryNotes:DB.config?.deliveryNotes||'', defaultLeadDays:DB.config?.defaultLeadDays||3
    };
    DB.orders.forEach(o=>{o.deliveryDate=o.deliveryDate||'';o.delivered=!!o.delivered;o.customerId=o.customerId||'';o.source=o.source||'manual';});
    DB.products.forEach(p=>{p.categoryId=p.categoryId||'';p.published=p.published??true;p.availability=p.availability||'sob_encomenda';p.description=p.description||'';p.sku=p.sku||'';});
    DB.meta={...(DB.meta||{}),version:V5};
    saveDB();
  }
  ensureSchema();

  // Menu consolidado na lógica operacional da PAfro.
  nav.splice(0,nav.length,
    ['dashboard','▦','Painel'],['orders','▧','Orçamentos'],['calendar','▣','Calendário'],['catalog','▤','Catálogo Online'],
    ['finance','▥','Financeiro'],['stock','▦','Estoque'],['pricing','◈','Precificação'],['reports','▥','Relatórios'],
    ['records','◆','Cadastros'],['settings','⚙','Configurações']
  );

  // ---------- Busca inteligente / autocomplete ----------
  function entityText(item){return item?.name||item?.customer||item?.description||item?.label||'';}
  function pickerHTML({id,label,items=[],selectedId='',placeholder='Digite para buscar…',span='span-6',help='',onpick='',allowClear=true}){
    const sel=items.find(x=>x.id===selectedId); const txt=sel?entityText(sel):'';
    return `<label class="field ${span}"><span class="label">${esc(label)}</span><div class="smart-picker" data-picker="${esc(id)}" data-onpick="${esc(onpick)}"><input type="hidden" id="${esc(id)}" class="picker-value" value="${esc(selectedId||'')}"><div class="picker-input-wrap"><input type="search" class="picker-input" autocomplete="off" placeholder="${esc(placeholder)}" value="${esc(txt)}"><button type="button" class="picker-clear ${allowClear?'':'hide'}" aria-label="Limpar">×</button></div><div class="picker-results hide">${items.map(x=>`<button type="button" class="picker-option" data-id="${esc(x.id)}" data-label="${esc(entityText(x))}">${esc(entityText(x))}</button>`).join('')}</div></div>${help?`<small>${help}</small>`:''}</label>`;
  }
  window.pickerHTML=pickerHTML;
  function bindSearchPickers(root=document){
    root.querySelectorAll('.smart-picker').forEach(box=>{
      if(box.dataset.bound==='1')return; box.dataset.bound='1';
      const input=box.querySelector('.picker-input'), hidden=box.querySelector('.picker-value'), results=box.querySelector('.picker-results'), clear=box.querySelector('.picker-clear');
      const all=[...box.querySelectorAll('.picker-option')];
      const filter=()=>{const term=normalize(input.value);let shown=0;all.forEach(b=>{const ok=!term||normalize(b.dataset.label).includes(term);b.classList.toggle('hide',!ok);if(ok)shown++;});results.classList.toggle('hide',!shown);};
      input.addEventListener('focus',filter);input.addEventListener('input',()=>{hidden.value='';filter();});
      all.forEach(b=>b.addEventListener('click',()=>{hidden.value=b.dataset.id;input.value=b.dataset.label;results.classList.add('hide');const cb=box.dataset.onpick;if(cb&&typeof window[cb]==='function')window[cb](b.dataset.id,box);}));
      clear?.addEventListener('click',()=>{hidden.value='';input.value='';results.classList.add('hide');input.focus();const cb=box.dataset.onpick;if(cb&&typeof window[cb]==='function')window[cb]('',box);});
      document.addEventListener('click',e=>{if(!box.contains(e.target))results.classList.add('hide');},{once:false});
    });
  }
  window.bindSearchPickers=bindSearchPickers;
  const oldBind=bindView;
  bindView=function(){oldBind();bindSearchPickers();bindGlobalSearch();};

  // Busca global no topo: produtos, insumos, clientes, fornecedores, pedidos.
  function globalSearchData(){return [
    ...DB.products.map(x=>({...x,_kind:'Produto',_view:'records',_tab:'products'})),
    ...DB.inputs.map(x=>({...x,_kind:'Insumo',_view:'records',_tab:'inputs'})),
    ...DB.suppliers.map(x=>({...x,_kind:'Fornecedor',_view:'records',_tab:'suppliers'})),
    ...DB.customers.map(x=>({...x,name:x.name,_kind:'Cliente',_view:'records',_tab:'customers'})),
    ...DB.orders.map(x=>({...x,name:`${x.customer||'Pedido'} · ${dateBR(x.date)}`,_kind:'Pedido',_view:'orders',_tab:''}))
  ];}
  function installGlobalSearch(){const top=document.querySelector('.topbar');if(!top||document.querySelector('#globalSearch'))return;top.insertAdjacentHTML('beforeend',`<div class="global-search"><input id="globalSearch" type="search" placeholder="Buscar produto, cliente, insumo, fornecedor ou pedido…" autocomplete="off"><div id="globalResults" class="global-results hide"></div></div>`);}
  function bindGlobalSearch(){installGlobalSearch();const inp=q('#globalSearch'),out=q('#globalResults');if(!inp||inp.dataset.bound)return;inp.dataset.bound='1';inp.oninput=()=>{const t=normalize(inp.value);if(t.length<2){out.classList.add('hide');return;}const hits=globalSearchData().filter(x=>normalize(entityText(x)).includes(t)||normalize(x.customer).includes(t)).slice(0,10);out.innerHTML=hits.map(x=>`<button data-gview="${x._view}" data-gtab="${x._tab}"><span class="pill blue">${x._kind}</span><b>${esc(entityText(x))}</b></button>`).join('')||`<div class="empty tiny">Nada encontrado.</div>`;out.classList.remove('hide');out.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.view=b.dataset.gview;state.tab=b.dataset.gtab||state.tab;inp.value='';out.classList.add('hide');render();});};inp.onfocus=()=>{if(inp.value.length>=2)inp.oninput();};}

  // ---------- Helpers de cadastro ----------
  const catName=id=>DB.categories.find(x=>x.id===id)?.name||'Sem categoria';
  const customerName=id=>DB.customers.find(x=>x.id===id)?.name||'';
  window.catName=catName; window.customerName=customerName;

  // ---------- Precificação: todos os cadastros pesquisáveis ----------
  calcForm=function(){const x=pricingFormValues();return `<div class="card"><h2>Monte o cenário</h2><div class="form-grid">
    ${pickerHTML({id:'pcProduct',label:'Produto',items:DB.products,selectedId:x.productId,placeholder:'Busque pelo nome do produto',span:'span-6',help:'Digite parte do nome. Não precisa percorrer uma lista.'})}
    <label class="field span-3"><span class="label">Quantidade</span><input id="pcQty" inputmode="numeric" value="${x.qty}"></label>
    ${pickerHTML({id:'pcPayment',label:'Pagamento',items:DB.payments.filter(p=>p.active),selectedId:x.paymentId,placeholder:'Busque a forma de pagamento',span:'span-3'})}
    <label class="field span-3"><span class="label">Quanto deve sobrar como lucro (%)</span><input id="pcMargin" inputmode="decimal" value="${x.marginPct}"><small>Margem real sobre o preço de venda.</small></label>
    <label class="field span-3"><span class="label">Reserva PAfro (%)</span><input id="pcReserve" inputmode="decimal" value="${x.reservePct}"></label>
    <label class="field span-3"><span class="label">Perda / desperdício (%)</span><input id="pcWaste" inputmode="decimal" value="${x.wastePct}"></label>
    <label class="field span-3"><span class="label">Impostos (%)</span><input id="pcTax" inputmode="decimal" value="${x.taxPct}"></label>
    <label class="field span-3"><span class="label">Desconto previsto (%)</span><input id="pcDiscount" inputmode="decimal" value="${x.discountPct}"><small>O preço de tabela sobe para preservar a conta após o desconto.</small></label>
  </div><div class="form-actions"><button class="btn primary" onclick="runPricing()">Calcular preço</button></div></div>`;};
  readCalcInputs=function(){return {productId:q('#pcProduct')?.value||'',qty:n(q('#pcQty')?.value)||1,paymentId:q('#pcPayment')?.value||DB.config.defaultPayment,marginPct:n(q('#pcMargin')?.value),reservePct:n(q('#pcReserve')?.value),wastePct:n(q('#pcWaste')?.value),taxPct:n(q('#pcTax')?.value),discountPct:n(q('#pcDiscount')?.value)};};

  // ---------- Produtos: categoria e insumos pesquisáveis ----------
  recipeRow=function(r={},i=0){return `<div class="form-grid recipe-row" style="margin-bottom:8px">${pickerHTML({id:`recipe_${i}_${uid('x')}`,label:i===0?'Insumo':'',items:DB.inputs,selectedId:r.inputId||'',placeholder:'Busque o insumo',span:'span-8'})}<label class="field span-3"><span class="label">${i===0?'Qtd. por unidade':''}</span><input class="recipe-qty" value="${n(r.qty)||1}"></label><div class="span-1" style="padding-top:${i===0?'25':'0'}px"><button type="button" class="btn small danger" onclick="this.closest('.recipe-row').remove()">×</button></div></div>`;};
  window.addRecipeRow=()=>{const c=q('#recipeRows');c.insertAdjacentHTML('beforeend',recipeRow({},c.children.length));bindSearchPickers(c);};
  productModal=function(p={}){const recipe=p.recipe||[];const rows=recipe.length?recipe:[{inputId:'',qty:1}];openModal(modalShell(p.id?'Editar produto':'Novo produto',`<div class="form-grid">
    <label class="field span-8"><span class="label">Nome do produto</span><input id="prdName" value="${esc(p.name||'')}"></label>
    ${pickerHTML({id:'prdCatId',label:'Categoria',items:DB.categories,selectedId:p.categoryId||'',placeholder:'Busque ou cadastre uma categoria',span:'span-4'})}
    <label class="field span-4"><span class="label">SKU / código</span><input id="prdSku" value="${esc(p.sku||'')}"></label>
    <label class="field span-4"><span class="label">Disponibilidade</span><select id="prdAvail"><option value="sob_encomenda" ${p.availability==='sob_encomenda'?'selected':''}>Sob encomenda</option><option value="pronta_entrega" ${p.availability==='pronta_entrega'?'selected':''}>Pronta entrega</option></select></label>
    <label class="field span-4"><span class="label">Publicar no catálogo</span><select id="prdPub"><option value="1" ${p.published!==false?'selected':''}>Sim</option><option value="0" ${p.published===false?'selected':''}>Não</option></select></label>
    <label class="field span-3"><span class="label">Tempo por unidade (min)</span><input id="prdMin" value="${n(p.productionMinutes)}"></label><label class="field span-3"><span class="label">Preparo fixo/pedido (min)</span><input id="prdSetup" value="${n(p.setupMinutes)}"></label><label class="field span-3"><span class="label">Embalagem/un.</span><input id="prdPack" value="${n(p.packaging)}"></label><label class="field span-3"><span class="label">Outros materiais/un.</span><input id="prdExtra" value="${n(p.extraMaterial)}"></label>
    <label class="field span-3"><span class="label">Terceiros/un.</span><input id="prdThird" value="${n(p.thirdParty)}"></label><label class="field span-3"><span class="label">Perda específica (%)</span><input id="prdWaste" placeholder="Padrão ${DB.config.wastePct}%" value="${p.wastePct??''}"></label><label class="field span-3"><span class="label">Preço de venda atual</span><input id="prdPrice" value="${n(p.salePrice)||''}"></label><label class="field span-3"><span class="label">Preço mínimo definido</span><input id="prdMinPrice" value="${n(p.minimumPrice)||''}"></label>
    <div class="span-12"><h3>Receita / insumos por unidade</h3><div id="recipeRows">${rows.map(recipeRow).join('')}</div><button class="btn small outline" type="button" onclick="addRecipeRow()">+ Adicionar insumo</button></div>
    <label class="field span-12"><span class="label">Descrição para catálogo</span><textarea id="prdDesc">${esc(p.description||'')}</textarea></label><label class="field span-12"><span class="label">Observações internas</span><textarea id="prdNote">${esc(p.note||'')}</textarea></label>
    </div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveProductV5('${p.id||''}')">Salvar produto</button>`));bindSearchPickers(q('#modalCard'));};
  window.saveProductV5=id=>{const name=q('#prdName').value.trim();if(!name)return toast('Informe o nome do produto.');const recipe=[...q('#recipeRows').querySelectorAll('.recipe-row')].map(r=>({inputId:r.querySelector('.picker-value')?.value||'',qty:n(r.querySelector('.recipe-qty')?.value)})).filter(r=>r.inputId&&r.qty>0);const old=productById(id);const catId=q('#prdCatId').value;const obj={id:id||uid('prd'),name,categoryId:catId,category:catName(catId)==='Sem categoria'?'':catName(catId),sku:q('#prdSku').value.trim(),availability:q('#prdAvail').value,published:q('#prdPub').value==='1',productionMinutes:n(q('#prdMin').value),setupMinutes:n(q('#prdSetup').value),packaging:n(q('#prdPack').value),extraMaterial:n(q('#prdExtra').value),thirdParty:n(q('#prdThird').value),wastePct:q('#prdWaste').value===''?null:n(q('#prdWaste').value),salePrice:n(q('#prdPrice').value),minimumPrice:n(q('#prdMinPrice').value),recipe,description:q('#prdDesc').value.trim(),note:q('#prdNote').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.products[DB.products.findIndex(x=>x.id===id)]=obj;else DB.products.push(obj);saveDB();closeModal();render();toast('Produto salvo.');};
  window.newProduct=()=>productModal({});window.editProduct=id=>productModal(productById(id));

  // ---------- Insumos / fornecedor pesquisável ----------
  inputModal=function(i={}){openModal(modalShell(i.id?'Editar insumo':'Novo insumo',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="inName" value="${esc(i.name||'')}"></label><label class="field span-3"><span class="label">Unidade</span><select id="inUnit">${['un','m','cm','kg','g','L','ml','folha','m²'].map(u=>`<option ${i.unit===u?'selected':''}>${u}</option>`).join('')}</select></label><label class="field span-3"><span class="label">Custo de referência (R$)</span><input id="inCost" value="${n(i.referenceCost)||''}"></label><label class="field span-4"><span class="label">Estoque atual</span><input id="inStock" value="${n(i.stock)}"></label><label class="field span-4"><span class="label">Estoque mínimo</span><input id="inMin" value="${n(i.minStock)}"></label>${pickerHTML({id:'inSup',label:'Fornecedor principal',items:DB.suppliers,selectedId:i.supplierId||'',placeholder:'Busque o fornecedor',span:'span-4'})}<label class="field span-12"><span class="label">Observação</span><textarea id="inNote">${esc(i.note||'')}</textarea></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveInputV5('${i.id||''}')">Salvar</button>`));bindSearchPickers(q('#modalCard'));};
  window.saveInputV5=id=>{const name=q('#inName').value.trim();if(!name)return toast('Informe o nome.');const old=inputById(id);const obj={id:id||uid('ins'),name,unit:q('#inUnit').value,referenceCost:n(q('#inCost').value),stock:n(q('#inStock').value),minStock:n(q('#inMin').value),supplierId:q('#inSup').value,note:q('#inNote').value.trim(),priceHistory:old?.priceHistory||[],createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.inputs[DB.inputs.findIndex(x=>x.id===id)]=obj;else DB.inputs.push(obj);saveDB();closeModal();render();toast('Insumo salvo.');};
  window.newInput=()=>inputModal({});window.editInput=id=>inputModal(inputById(id));
  window.registerInputPrice=id=>{const i=inputById(id);openModal(modalShell('Registrar preço encontrado',`<div class="form-grid"><label class="field span-4"><span class="label">Preço encontrado</span><input id="rpValue"></label><label class="field span-4"><span class="label">Data</span><input type="date" id="rpDate" value="${today()}"></label>${pickerHTML({id:'rpSup',label:'Fornecedor',items:DB.suppliers,selectedId:i.supplierId||'',placeholder:'Busque o fornecedor',span:'span-4'})}<label class="field span-12"><span class="label">Observação</span><input id="rpNote"></label><label class="field span-12"><input type="checkbox" id="rpRef" style="width:auto"> <b>Usar este valor como novo custo de referência</b></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveInputPrice('${id}')">Registrar</button>`));bindSearchPickers(q('#modalCard'));};

  // ---------- Estoque pesquisável ----------
  window.newStockMove=()=>{openModal(modalShell('Movimentar estoque',`<div class="form-grid">${pickerHTML({id:'smInput',label:'Insumo',items:DB.inputs,placeholder:'Busque o insumo',span:'span-6'})}<label class="field span-3"><span class="label">Tipo</span><select id="smType"><option value="in">Entrada</option><option value="out">Saída</option></select></label><label class="field span-3"><span class="label">Quantidade</span><input id="smQty"></label><label class="field span-4"><span class="label">Data</span><input type="date" id="smDate" value="${today()}"></label><label class="field span-8"><span class="label">Motivo</span><input id="smReason" placeholder="Compra, produção, ajuste…"></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveStockMoveV5()">Salvar</button>`));bindSearchPickers(q('#modalCard'));};
  window.saveStockMoveV5=()=>{const id=q('#smInput').value,qty=n(q('#smQty').value),i=inputById(id);if(!i||qty<=0)return toast('Escolha o insumo e informe a quantidade.');const type=q('#smType').value;i.stock=n(i.stock)+(type==='in'?qty:-qty);DB.stockMoves.push({id:uid('mov'),inputId:id,type,qty,date:q('#smDate').value||today(),reason:q('#smReason').value.trim()});saveDB();closeModal();render();};

  // ---------- Clientes ----------
  function renderCustomers(){const term=state.recordSearch||'';const arr=DB.customers.filter(c=>!term||normalize([c.name,c.phone,c.email].join(' ')).includes(normalize(term)));return `${pageHead('Clientes','Cadastro reutilizável para orçamentos, vendas e relatórios.',`<button class="btn yellow" onclick="newCustomer()">+ Novo cliente</button>`)}${searchBar('recordSearch','Buscar cliente por nome, telefone ou e-mail',term)}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>WhatsApp</th><th>E-mail</th><th>Nascimento</th><th>Pedidos</th><th>Ações</th></tr></thead><tbody>${arr.length?arr.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td><td>${dateBR(c.birthDate)}</td><td>${DB.orders.filter(o=>o.customerId===c.id).length}</td><td><button class="btn small blue" onclick="editCustomer('${c.id}')">Editar</button> <button class="btn small danger" onclick="deleteCustomer('${c.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">Nenhum cliente encontrado.</div></td></tr>`}</tbody></table></div></div>`;}
  function customerModal(c={}){openModal(modalShell(c.id?'Editar cliente':'Novo cliente',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="cuName" value="${esc(c.name||'')}"></label><label class="field span-3"><span class="label">WhatsApp</span><input id="cuPhone" value="${esc(c.phone||'')}"></label><label class="field span-3"><span class="label">Data de nascimento</span><input type="date" id="cuBirth" value="${c.birthDate||''}"></label><label class="field span-6"><span class="label">E-mail</span><input id="cuEmail" value="${esc(c.email||'')}"></label><label class="field span-6"><span class="label">Instagram / origem</span><input id="cuSource" value="${esc(c.source||'')}"></label><label class="field span-12"><span class="label">Observações</span><textarea id="cuNote">${esc(c.note||'')}</textarea></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveCustomer('${c.id||''}')">Salvar</button>`));}
  window.newCustomer=()=>customerModal({});window.editCustomer=id=>customerModal(DB.customers.find(x=>x.id===id));window.saveCustomer=id=>{const name=q('#cuName').value.trim();if(!name)return toast('Informe o nome.');const old=DB.customers.find(x=>x.id===id);const o={id:id||uid('cus'),name,phone:q('#cuPhone').value.trim(),email:q('#cuEmail').value.trim(),birthDate:q('#cuBirth').value,source:q('#cuSource').value.trim(),note:q('#cuNote').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.customers[DB.customers.findIndex(x=>x.id===id)]=o;else DB.customers.push(o);saveDB();closeModal();render();};window.deleteCustomer=id=>{if(confirm('Excluir cliente? Os pedidos antigos permanecerão.')){DB.customers=DB.customers.filter(x=>x.id!==id);saveDB();render();}};

  // ---------- Categorias ----------
  function renderCategories(){return `${pageHead('Categorias','Organize produtos para o catálogo e para as buscas.',`<button class="btn yellow" onclick="newCategory()">+ Nova categoria</button>`)}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Categoria</th><th>Descrição</th><th>Produtos</th><th>Ordem</th><th>Ações</th></tr></thead><tbody>${DB.categories.length?DB.categories.sort((a,b)=>n(a.order)-n(b.order)).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.description||'')}</td><td>${DB.products.filter(p=>p.categoryId===c.id).length}</td><td>${n(c.order)}</td><td><button class="btn small blue" onclick="editCategory('${c.id}')">Editar</button> <button class="btn small danger" onclick="deleteCategory('${c.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="5"><div class="empty">Nenhuma categoria.</div></td></tr>`}</tbody></table></div></div>`;}
  function categoryModal(c={}){openModal(modalShell(c.id?'Editar categoria':'Nova categoria',`<div class="form-grid"><label class="field span-6"><span class="label">Nome</span><input id="ctName" value="${esc(c.name||'')}"></label><label class="field span-2"><span class="label">Ordem</span><input id="ctOrder" value="${n(c.order)}"></label><label class="field span-4"><span class="label">Publicada</span><select id="ctPub"><option value="1" ${c.published!==false?'selected':''}>Sim</option><option value="0" ${c.published===false?'selected':''}>Não</option></select></label><label class="field span-12"><span class="label">Descrição</span><input id="ctDesc" value="${esc(c.description||'')}"></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveCategory('${c.id||''}')">Salvar</button>`));}
  window.newCategory=()=>categoryModal({published:true});window.editCategory=id=>categoryModal(DB.categories.find(x=>x.id===id));window.saveCategory=id=>{const name=q('#ctName').value.trim();if(!name)return toast('Informe o nome.');const old=DB.categories.find(x=>x.id===id);const o={id:id||uid('cat'),name,description:q('#ctDesc').value.trim(),order:n(q('#ctOrder').value),published:q('#ctPub').value==='1',createdAt:old?.createdAt||new Date().toISOString()};if(id)DB.categories[DB.categories.findIndex(x=>x.id===id)]=o;else DB.categories.push(o);saveDB();closeModal();render();};window.deleteCategory=id=>{if(DB.products.some(p=>p.categoryId===id)&&!confirm('Há produtos nesta categoria. Remover mesmo assim?'))return;DB.products.forEach(p=>{if(p.categoryId===id){p.categoryId='';p.category='';}});DB.categories=DB.categories.filter(x=>x.id!==id);saveDB();render();};

  function searchBar(key,placeholder,value=''){return `<div class="search-strip"><input type="search" placeholder="${esc(placeholder)}" value="${esc(value)}" oninput="setSearchState('${key}',this.value)"></div>`;}
  window.setSearchState=(k,v)=>{state[k]=v;clearTimeout(window.__srch);window.__srch=setTimeout(render,120);};

  // ---------- Cadastros consolidado ----------
  function renderRecords(){const tabs=[['products','Produtos'],['inputs','Insumos'],['suppliers','Fornecedores'],['customers','Clientes'],['categories','Categorias']];if(!tabs.some(x=>x[0]===state.tab))state.tab='products';const subt=`<div class="subtabs">${tabs.map(x=>`<button class="subtab ${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div>`;const body=state.tab==='products'?renderProducts():state.tab==='inputs'?renderInputs():state.tab==='suppliers'?renderSuppliers():state.tab==='customers'?renderCustomers():renderCategories();return subt+body;}

  // ---------- Orçamentos / pedidos com cliente, produto e pagamento pesquisáveis ----------
  orderItemRow=function(it={}){const rid=uid('oi');return `<div class="form-grid order-item" style="margin-bottom:10px">${pickerHTML({id:`oiProd_${rid}`,label:'Produto / item cadastrado',items:DB.products,selectedId:it.productId||'',placeholder:'Busque o produto',span:'span-5',onpick:'fillOrderItemV5'})}<label class="field span-3"><span class="label">Nome no orçamento</span><input class="oiName" value="${esc(it.name||'')}"></label><label class="field span-1"><span class="label">Qtd.</span><input class="oiQty" value="${n(it.qty)||1}"></label><label class="field span-1"><span class="label">R$/un</span><input class="oiPrice" value="${n(it.unitPrice)||''}"></label><label class="field span-1"><span class="label">Custo/un</span><input class="oiCost" value="${n(it.costUnit)||''}"></label><div class="span-1" style="padding-top:25px"><button class="btn small danger" onclick="this.closest('.order-item').remove()">×</button></div></div>`;};
  window.fillOrderItemV5=(id,box)=>{const row=box.closest('.order-item'),p=productById(id);if(!p)return;row.querySelector('.oiName').value=p.name;row.querySelector('.oiPrice').value=p.salePrice||'';const pay=q('#odPay')?.value||DB.config.defaultPayment;const r=calculatePrice({productId:p.id,qty:1,paymentId:pay,marginPct:DB.config.targetMarginRetail});row.querySelector('.oiCost').value=r.protectedUnit.toFixed(2).replace('.',',');};
  orderModal=function(o={}){const items=o.items?.length?o.items:[{}];openModal(modalShell(o.id?'Editar pedido':'Novo orçamento',`<div class="form-grid">
    ${pickerHTML({id:'odCustomerId',label:'Cliente',items:DB.customers,selectedId:o.customerId||'',placeholder:'Busque o cliente',span:'span-5',onpick:'pickOrderCustomer'})}<label class="field span-3"><span class="label">Nome exibido</span><input id="odCustomer" value="${esc(o.customer||customerName(o.customerId)||'')}"></label><label class="field span-2"><span class="label">Data</span><input type="date" id="odDate" value="${o.date||today()}"></label><label class="field span-2"><span class="label">Entrega</span><input type="date" id="odDelivery" value="${o.deliveryDate||''}"></label>
    <label class="field span-3"><span class="label">Status</span><select id="odStatus">${['orcamento','aprovado','producao','pago','finalizado','cancelado'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></label>${pickerHTML({id:'odPay',label:'Pagamento',items:DB.payments,selectedId:o.paymentId||DB.config.defaultPayment,placeholder:'Busque o pagamento',span:'span-4'})}<label class="field span-2"><span class="label">Entregue?</span><select id="odDelivered"><option value="0" ${!o.delivered?'selected':''}>Não</option><option value="1" ${o.delivered?'selected':''}>Sim</option></select></label><label class="field span-3"><span class="label">Origem</span><select id="odSource"><option value="manual" ${o.source!=='catalogo'?'selected':''}>Manual / atendimento</option><option value="catalogo" ${o.source==='catalogo'?'selected':''}>Catálogo online</option></select></label>
    <div class="span-12"><h3>Itens</h3><div id="orderItems">${items.map(orderItemRow).join('')}</div><button class="btn small outline" onclick="addOrderItemV5()">+ Item</button></div><label class="field span-12"><span class="label">Observações</span><textarea id="odNote">${esc(o.note||'')}</textarea></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveOrderV5('${o.id||''}')">Salvar</button>`));bindSearchPickers(q('#modalCard'));};
  window.pickOrderCustomer=(id)=>{const c=DB.customers.find(x=>x.id===id);if(c)q('#odCustomer').value=c.name;};
  window.addOrderItemV5=()=>{q('#orderItems').insertAdjacentHTML('beforeend',orderItemRow({}));bindSearchPickers(q('#orderItems'));};
  window.newOrder=()=>orderModal({status:'orcamento',paymentId:DB.config.defaultPayment});window.editOrder=id=>orderModal(DB.orders.find(x=>x.id===id));
  window.saveOrderV5=id=>{const items=[...document.querySelectorAll('.order-item')].map(r=>({productId:r.querySelector('.picker-value')?.value||'',name:r.querySelector('.oiName').value.trim(),qty:Math.max(1,n(r.querySelector('.oiQty').value)||1),unitPrice:n(r.querySelector('.oiPrice').value),costUnit:n(r.querySelector('.oiCost').value)})).filter(i=>i.name&&i.unitPrice>=0);if(!items.length)return toast('Inclua pelo menos um item.');const total=items.reduce((s,i)=>s+i.qty*i.unitPrice,0),cost=items.reduce((s,i)=>s+i.qty*i.costUnit,0);const pay=paymentById(q('#odPay').value),fees=total*n(pay.pct)/100+n(pay.fixed),taxes=total*n(DB.config.taxPct)/100,profit=total-cost-fees-taxes;const old=DB.orders.find(x=>x.id===id);const status=q('#odStatus').value;const obj={id:id||uid('ord'),customerId:q('#odCustomerId').value,customer:q('#odCustomer').value.trim(),date:q('#odDate').value||today(),deliveryDate:q('#odDelivery').value,status,delivered:q('#odDelivered').value==='1',paymentId:pay.id,source:q('#odSource').value,items,total,cost,estimatedProfit:profit,note:q('#odNote').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)DB.orders[DB.orders.findIndex(x=>x.id===id)]=obj;else DB.orders.push(obj);if(status==='pago'&&!DB.finance.some(f=>f.orderId===obj.id))DB.finance.push({id:uid('fin'),date:obj.date,type:'income',category:'Vendas',description:`Pedido ${obj.customer||obj.id}`,amount:obj.total,orderId:obj.id,paymentId:obj.paymentId});saveDB();closeModal();render();toast('Pedido salvo.');};
  renderOrders=function(){const term=state.orderSearch||'';const orders=[...DB.orders].filter(o=>!term||normalize([o.customer,...(o.items||[]).map(i=>i.name),statusLabel(o.status)].join(' ')).includes(normalize(term))).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `${pageHead('Orçamentos & Pedidos','Orçamento, aprovação, produção, pagamento e entrega no mesmo fluxo.',`<button class="btn yellow" onclick="newOrder()">+ Novo orçamento</button>`)}${searchBar('orderSearch','Buscar cliente, item ou status',term)}<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Entrega</th><th>Cliente</th><th>Status</th><th>Itens</th><th class="money">Total</th><th>Pagamento</th><th>Ações</th></tr></thead><tbody>${orders.length?orders.map(o=>`<tr><td>${dateBR(o.date)}</td><td>${dateBR(o.deliveryDate)}</td><td><b>${esc(o.customer||customerName(o.customerId)||'Cliente')}</b></td><td><span class="pill ${o.status==='cancelado'?'bad':o.status==='finalizado'||o.status==='pago'?'good':'blue'}">${statusLabel(o.status)}</span>${o.delivered?' <span class="pill good">Entregue</span>':''}</td><td>${(o.items||[]).map(i=>`${esc(i.name)} × ${i.qty}`).join('<br>')}</td><td class="money strong">${money(o.total)}</td><td>${esc(paymentById(o.paymentId).name)}</td><td><button class="btn small blue" onclick="editOrder('${o.id}')">Editar</button> <button class="btn small danger" onclick="deleteOrder('${o.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty">Nenhum pedido encontrado.</div></td></tr>`}</tbody></table></div></div>`;};

  // ---------- Calendário de entregas ----------
  function renderCalendar(){const withDate=DB.orders.filter(o=>o.deliveryDate&&['aprovado','producao','pago','finalizado'].includes(o.status)&&!o.delivered).sort((a,b)=>a.deliveryDate.localeCompare(b.deliveryDate));const by={};withDate.forEach(o=>(by[o.deliveryDate]=by[o.deliveryDate]||[]).push(o));return `${pageHead('Calendário','Entregas puxadas automaticamente dos pedidos aprovados, em produção ou ainda não entregues.',`<button class="btn yellow" onclick="newOrder()">+ Novo orçamento</button>`)}<div class="calendar-grid">${Object.keys(by).length?Object.entries(by).map(([d,os])=>`<div class="card calendar-day"><div class="calendar-date"><b>${dateBR(d)}</b><span>${os.length} entrega(s)</span></div>${os.map(o=>`<button class="calendar-order" onclick="editOrder('${o.id}')"><b>${esc(o.customer||'Cliente')}</b><span>${(o.items||[]).map(i=>`${i.name} × ${i.qty}`).join(', ')}</span><span class="pill blue">${statusLabel(o.status)}</span></button>`).join('')}</div>`).join(''):`<div class="card"><div class="empty">Nenhuma entrega pendente com data definida.</div></div>`}</div>`;}

  // ---------- Catálogo Online ----------
  function catalogTabs(){const tabs=[['overview','Visão geral'],['catalogProducts','Produtos'],['categories','Categorias'],['catalogConfig','Configuração'],['links','Links'],['hours','Horários'],['coupons','Cupons'],['sales','Vendas'],['activation','Ativação']];if(!tabs.some(x=>x[0]===state.tab))state.tab='overview';return `<div class="subtabs">${tabs.map(x=>`<button class="subtab ${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div>`;}
  function renderCatalog(){let body='';if(state.tab==='catalogProducts')body=renderCatalogProducts();else if(state.tab==='categories')body=renderCategories();else if(state.tab==='catalogConfig')body=renderCatalogConfig();else if(state.tab==='links')body=renderLinks();else if(state.tab==='hours')body=renderHours();else if(state.tab==='coupons')body=renderCoupons();else if(state.tab==='sales')body=renderCatalogSales();else if(state.tab==='activation')body=renderActivation();else body=renderCatalogOverview();return `${pageHead('Catálogo Online','Organize o que o cliente vê e acompanhe as vendas originadas pelo catálogo.',`<button class="btn yellow" onclick="newProduct()">+ Novo produto</button>`)}${catalogTabs()}${body}`;}
  function activationChecks(){return [
    ['Dados do negócio',!!DB.config.businessName&&!!DB.config.businessPhone],['Logo da marca',true],['Slogan',!!DB.config.catalogSlogan],['Produtos publicados',DB.products.some(p=>p.published)],['Fotos dos produtos','warn'],['Descrições completas',DB.products.some(p=>p.description)],['Categorias',DB.categories.length>0],['WhatsApp',!!DB.config.whatsappLink||!!DB.config.businessPhone],['Horários',DB.businessHours.length>0],['Link do catálogo',DB.catalogLinks.length>0],['Meios de pagamento',DB.payments.length>0],['Cupons (opcional)','optional']];}
  function renderCatalogOverview(){const checks=activationChecks(),ok=checks.filter(x=>x[1]===true).length;return `<div class="grid cols-3"><div class="card kpi accent-yellow"><div class="label">Produtos publicados</div><div class="value">${DB.products.filter(p=>p.published).length}</div></div><div class="card kpi accent-blue"><div class="label">Categorias</div><div class="value">${DB.categories.length}</div></div><div class="card kpi accent-pink"><div class="label">Ativação</div><div class="value">${ok}/${checks.filter(x=>x[1]!=='optional').length}</div></div></div><div class="card" style="margin-top:14px"><h2>Prévia da loja</h2><div class="catalog-preview"><img src="logo-pafro.png" alt="Papel Afro"><h3>${esc(DB.config.businessName||'Papel Afro')}</h3><p>${esc(DB.config.catalogSlogan)}</p><div class="catalog-grid">${DB.products.filter(p=>p.published).slice(0,6).map(p=>`<div class="product-card"><div class="product-icon">💡</div><h3>${esc(p.name)}</h3><p>${esc(catName(p.categoryId))}</p><div class="price">${p.salePrice?money(p.salePrice):'Sob consulta'}</div></div>`).join('')||'<div class="empty">Publique produtos para visualizar.</div>'}</div></div></div>`;}
  function renderCatalogProducts(){const term=state.catalogSearch||'';const arr=DB.products.filter(p=>!term||normalize([p.name,catName(p.categoryId),p.description].join(' ')).includes(normalize(term)));return `${searchBar('catalogSearch','Buscar produto no catálogo',term)}<div class="catalog-grid">${arr.map(p=>`<div class="product-card"><div class="product-icon">💡</div><h3>${esc(p.name)}</h3><p>${esc(catName(p.categoryId))} · ${p.availability==='pronta_entrega'?'Pronta entrega':'Sob encomenda'}</p><div class="price">${p.salePrice?money(p.salePrice):'Sem preço'}</div><p>${esc(p.description||'Sem descrição para o catálogo.')}</p><div class="form-actions"><span class="pill ${p.published?'good':'dark'}">${p.published?'Publicado':'Oculto'}</span><button class="btn small blue" onclick="editProduct('${p.id}')">Editar</button></div></div>`).join('')||'<div class="card"><div class="empty">Nenhum produto encontrado.</div></div>'}</div>`;}
  function renderCatalogConfig(){const c=DB.config;return `<div class="card"><h2>Configuração da loja</h2><div class="form-grid"><label class="field span-6"><span class="label">Nome do negócio</span><input id="cgBusiness" value="${esc(c.businessName)}"></label><label class="field span-6"><span class="label">Slogan</span><input id="cgSlogan" value="${esc(c.catalogSlogan)}"></label><label class="field span-4"><span class="label">Telefone</span><input id="cgPhone" value="${esc(c.businessPhone)}"></label><label class="field span-4"><span class="label">E-mail</span><input id="cgEmail" value="${esc(c.businessEmail)}"></label><label class="field span-4"><span class="label">WhatsApp / link curto</span><input id="cgWhats" value="${esc(c.whatsappLink)}"></label><label class="field span-4"><span class="label">Slug do catálogo</span><input id="cgSlug" value="${esc(c.catalogSlug)}"></label><label class="field span-4"><span class="label">Cor principal</span><input type="color" id="cgColor" value="${esc(c.catalogColor)}"></label><label class="field span-4"><span class="label">Catálogo ativo</span><select id="cgActive"><option value="1" ${c.catalogActive?'selected':''}>Sim</option><option value="0" ${!c.catalogActive?'selected':''}>Não</option></select></label><label class="field span-12"><span class="label">Apresentação</span><textarea id="cgIntro">${esc(c.catalogIntro)}</textarea></label><label class="field span-12"><span class="label">Informações de entrega</span><textarea id="cgDelivery">${esc(c.deliveryNotes)}</textarea></label></div><div class="form-actions"><button class="btn primary" onclick="saveCatalogConfig()">Salvar configuração</button></div></div>`;}
  window.saveCatalogConfig=()=>{Object.assign(DB.config,{businessName:q('#cgBusiness').value.trim(),catalogSlogan:q('#cgSlogan').value.trim(),businessPhone:q('#cgPhone').value.trim(),businessEmail:q('#cgEmail').value.trim(),whatsappLink:q('#cgWhats').value.trim(),catalogSlug:q('#cgSlug').value.trim(),catalogColor:q('#cgColor').value,catalogActive:q('#cgActive').value==='1',catalogIntro:q('#cgIntro').value.trim(),deliveryNotes:q('#cgDelivery').value.trim()});saveDB();render();toast('Catálogo atualizado.');};
  function renderLinks(){return `<div class="card"><div class="page-head"><div><h2>Links</h2><p class="muted">Atalhos que podem ser divulgados junto ao catálogo.</p></div><button class="btn yellow" onclick="newCatalogLink()">+ Novo link</button></div>${DB.catalogLinks.length?DB.catalogLinks.map(l=>`<div class="break-row"><span><b>${esc(l.label)}</b><br><span class="tiny muted">${esc(l.url)}</span></span><span><button class="btn small blue" onclick="editCatalogLink('${l.id}')">Editar</button> <button class="btn small danger" onclick="deleteCatalogLink('${l.id}')">Excluir</button></span></div>`).join(''):'<div class="empty">Nenhum link cadastrado.</div>'}</div>`;}
  function linkModal(l={}){openModal(modalShell(l.id?'Editar link':'Novo link',`<div class="form-grid"><label class="field span-5"><span class="label">Nome</span><input id="lkLabel" value="${esc(l.label||'')}"></label><label class="field span-7"><span class="label">URL</span><input id="lkUrl" value="${esc(l.url||'')}"></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveCatalogLink('${l.id||''}')">Salvar</button>`));}
  window.newCatalogLink=()=>linkModal({});window.editCatalogLink=id=>linkModal(DB.catalogLinks.find(x=>x.id===id));window.saveCatalogLink=id=>{const o={id:id||uid('lnk'),label:q('#lkLabel').value.trim(),url:q('#lkUrl').value.trim()};if(!o.label||!o.url)return toast('Preencha nome e URL.');if(id)DB.catalogLinks[DB.catalogLinks.findIndex(x=>x.id===id)]=o;else DB.catalogLinks.push(o);saveDB();closeModal();render();};window.deleteCatalogLink=id=>{DB.catalogLinks=DB.catalogLinks.filter(x=>x.id!==id);saveDB();render();};
  function renderHours(){const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];return `<div class="card"><h2>Horários de atendimento</h2><p class="muted">Defina os horários que aparecem para o cliente.</p>${days.map((d,i)=>{const h=DB.businessHours.find(x=>x.day===i)||{day:i,active:i<5,start:'09:00',end:'18:00'};return `<div class="hours-row"><b>${d}</b><label><input type="checkbox" class="hrActive" data-day="${i}" ${h.active?'checked':''}> Atende</label><input type="time" class="hrStart" data-day="${i}" value="${h.start||'09:00'}"><span>até</span><input type="time" class="hrEnd" data-day="${i}" value="${h.end||'18:00'}"></div>`}).join('')}<div class="form-actions"><button class="btn primary" onclick="saveHours()">Salvar horários</button></div></div>`;}
  window.saveHours=()=>{DB.businessHours=[0,1,2,3,4,5,6].map(day=>({day,active:q(`.hrActive[data-day="${day}"]`).checked,start:q(`.hrStart[data-day="${day}"]`).value,end:q(`.hrEnd[data-day="${day}"]`).value}));saveDB();toast('Horários salvos.');};
  function renderCoupons(){return `<div class="card"><div class="page-head"><div><h2>Cupons</h2><p class="muted">Descontos controlados para ações comerciais.</p></div><button class="btn yellow" onclick="newCoupon()">+ Novo cupom</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Tipo</th><th class="money">Valor</th><th>Validade</th><th>Status</th><th></th></tr></thead><tbody>${DB.coupons.length?DB.coupons.map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${c.type==='pct'?'Percentual':'Valor fixo'}</td><td class="money">${c.type==='pct'?pct(c.value):money(c.value)}</td><td>${dateBR(c.until)}</td><td><span class="pill ${c.active?'good':'dark'}">${c.active?'Ativo':'Inativo'}</span></td><td><button class="btn small blue" onclick="editCoupon('${c.id}')">Editar</button> <button class="btn small danger" onclick="deleteCoupon('${c.id}')">Excluir</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">Nenhum cupom.</div></td></tr>`}</tbody></table></div></div>`;}
  function couponModal(c={}){openModal(modalShell(c.id?'Editar cupom':'Novo cupom',`<div class="form-grid"><label class="field span-4"><span class="label">Código</span><input id="cpCode" value="${esc(c.code||'')}"></label><label class="field span-3"><span class="label">Tipo</span><select id="cpType"><option value="pct" ${c.type!=='fixed'?'selected':''}>Percentual</option><option value="fixed" ${c.type==='fixed'?'selected':''}>Valor fixo</option></select></label><label class="field span-2"><span class="label">Valor</span><input id="cpValue" value="${n(c.value)||''}"></label><label class="field span-3"><span class="label">Validade</span><input type="date" id="cpUntil" value="${c.until||''}"></label><label class="field span-4"><span class="label">Pedido mínimo</span><input id="cpMin" value="${n(c.minOrder)||''}"></label><label class="field span-4"><span class="label">Uso máximo</span><input id="cpMax" value="${n(c.maxUses)||''}"></label><label class="field span-4"><span class="label">Ativo</span><select id="cpActive"><option value="1" ${c.active!==false?'selected':''}>Sim</option><option value="0" ${c.active===false?'selected':''}>Não</option></select></label></div>`,`<button class="btn outline" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveCoupon('${c.id||''}')">Salvar</button>`));}
  window.newCoupon=()=>couponModal({active:true,type:'pct'});window.editCoupon=id=>couponModal(DB.coupons.find(x=>x.id===id));window.saveCoupon=id=>{const o={id:id||uid('cp'),code:q('#cpCode').value.trim().toUpperCase(),type:q('#cpType').value,value:n(q('#cpValue').value),until:q('#cpUntil').value,minOrder:n(q('#cpMin').value),maxUses:n(q('#cpMax').value),active:q('#cpActive').value==='1'};if(!o.code||o.value<=0)return toast('Informe código e valor.');if(id)DB.coupons[DB.coupons.findIndex(x=>x.id===id)]=o;else DB.coupons.push(o);saveDB();closeModal();render();};window.deleteCoupon=id=>{DB.coupons=DB.coupons.filter(x=>x.id!==id);saveDB();render();};
  function renderCatalogSales(){const sales=DB.orders.filter(o=>o.source==='catalogo').sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `<div class="notice blue">Toda venda marcada como <b>Catálogo online</b> continua sendo um pedido normal: entra nos relatórios e no financeiro quando paga.</div><div class="card" style="margin-top:14px"><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Cliente</th><th>Itens</th><th>Entrega</th><th class="money">Total</th><th>Situação</th></tr></thead><tbody>${sales.length?sales.map(o=>`<tr><td>${dateBR(o.date)}</td><td>${esc(o.customer)}</td><td>${o.items.length}</td><td>${dateBR(o.deliveryDate)}</td><td class="money">${money(o.total)}</td><td>${statusLabel(o.status)}</td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">Nenhuma venda do catálogo ainda.</div></td></tr>`}</tbody></table></div></div>`;}
  function renderActivation(){const checks=activationChecks();return `<div class="card"><h2>Checklist de ativação</h2><p class="muted">A ideia é evitar divulgar uma loja que ainda parece incompleta.</p>${checks.map(([nme,ok])=>`<div class="check-row"><span class="check-icon ${ok===true?'ok':ok==='optional'?'optional':'warn'}">${ok===true?'✓':ok==='optional'?'•':'!'}</span><div><b>${esc(nme)}</b><div class="tiny muted">${ok===true?'Pronto':ok==='optional'?'Opcional':'Vale completar antes de divulgar'}</div></div></div>`).join('')}</div>`;}

  // ---------- Relatórios consolidados ----------
  function reportTabs(){const tabs=[['ordersReport','Pedidos'],['productReport','Por produto'],['clientsReport','Clientes'],['financeReport','Financeiro']];if(!tabs.some(x=>x[0]===state.tab))state.tab='ordersReport';return `<div class="subtabs">${tabs.map(x=>`<button class="subtab ${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div>`;}
  function validOrders(){return DB.orders.filter(o=>['aprovado','producao','pago','finalizado'].includes(o.status));}
  function reportOrders(){const v=validOrders(),rev=v.reduce((s,o)=>s+n(o.total),0),items=v.reduce((s,o)=>s+(o.items||[]).reduce((a,i)=>a+n(i.qty),0),0);const byStatus={};v.forEach(o=>byStatus[o.status]=(byStatus[o.status]||0)+1);return `<div class="grid cols-4"><div class="card kpi accent-blue"><div class="label">Total pedidos</div><div class="value">${v.length}</div></div><div class="card kpi accent-yellow"><div class="label">Total itens</div><div class="value">${items}</div></div><div class="card kpi accent-pink"><div class="label">Ticket médio pedido</div><div class="value">${money(v.length?rev/v.length:0)}</div></div><div class="card kpi accent-dark"><div class="label">Ticket médio item</div><div class="value">${money(items?rev/items:0)}</div></div></div><div class="grid cols-2" style="margin-top:14px"><div class="card"><h2>Itens mais pedidos</h2>${reportProductTable(v)}</div><div class="card"><h2>Pedidos por status</h2>${Object.entries(byStatus).map(([s,c])=>`<div class="break-row"><span>${statusLabel(s)}</span><b>${c}</b></div>`).join('')||'<div class="empty">Sem dados.</div>'}</div></div>`;}
  function aggregateProducts(v,term=''){const by={};v.forEach(o=>(o.items||[]).forEach(i=>{if(term&&!normalize(i.name).includes(normalize(term)))return;const k=normalize(i.name);by[k]=by[k]||{name:i.name,qty:0,orders:new Set(),value:0};by[k].qty+=n(i.qty);by[k].orders.add(o.id);by[k].value+=n(i.qty)*n(i.unitPrice);}));return Object.values(by).map(x=>({...x,orders:x.orders.size})).sort((a,b)=>b.value-a.value);}
  function reportProductTable(v,term=''){const arr=aggregateProducts(v,term);return `<div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th class="money">Unidades</th><th class="money">Pedidos</th><th class="money">Valor</th></tr></thead><tbody>${arr.length?arr.map(x=>`<tr><td>${esc(x.name)}</td><td class="money">${x.qty}</td><td class="money">${x.orders}</td><td class="money">${money(x.value)}</td></tr>`).join(''):`<tr><td colspan="4"><div class="empty">Sem itens.</div></td></tr>`}</tbody></table></div>`;}
  function reportProduct(){const term=state.reportProductSearch||'';return `<div class="notice blue">Digite só uma parte do nome para somar variações — por exemplo, “caneca”.</div>${searchBar('reportProductSearch','Buscar produto ou parte do nome',term)}<div class="card">${reportProductTable(validOrders(),term)}</div>`;}
  function reportClients(){const v=validOrders(),by={};v.forEach(o=>{const key=o.customerId||normalize(o.customer||'Sem cliente');by[key]=by[key]||{name:o.customer||customerName(o.customerId)||'Sem cliente',phone:DB.customers.find(c=>c.id===o.customerId)?.phone||'',orders:0,total:0,last:''};by[key].orders++;by[key].total+=n(o.total);if(!by[key].last||o.date>by[key].last)by[key].last=o.date;});const arr=Object.values(by).sort((a,b)=>b.total-a.total);return `<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>WhatsApp</th><th class="money">Pedidos</th><th class="money">Ticket médio</th><th class="money">Total gasto</th><th>Último pedido</th></tr></thead><tbody>${arr.length?arr.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone||'—')}</td><td class="money">${c.orders}</td><td class="money">${money(c.total/c.orders)}</td><td class="money">${money(c.total)}</td><td>${dateBR(c.last)}</td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">Sem clientes nos pedidos.</div></td></tr>`}</tbody></table></div></div>`;}
  function reportFinance(){const inc=DB.finance.filter(x=>x.type==='income'),exp=DB.finance.filter(x=>x.type==='expense'),sum=a=>a.reduce((s,x)=>s+n(x.amount),0);const pay={};validOrders().forEach(o=>pay[o.paymentId]=(pay[o.paymentId]||0)+n(o.total));const open=DB.orders.filter(o=>['aprovado','producao'].includes(o.status));return `<div class="grid cols-3"><div class="card kpi accent-blue"><div class="label">Receitas</div><div class="value">${money(sum(inc))}</div></div><div class="card kpi accent-pink"><div class="label">Gastos</div><div class="value">${money(sum(exp))}</div></div><div class="card kpi accent-yellow"><div class="label">Saldo</div><div class="value">${money(sum(inc)-sum(exp))}</div></div></div><div class="grid cols-2" style="margin-top:14px"><div class="card"><h2>Receita por forma de pagamento</h2>${Object.entries(pay).map(([id,v])=>`<div class="break-row"><span>${esc(paymentById(id).name)}</span><b>${money(v)}</b></div>`).join('')||'<div class="empty">Sem dados.</div>'}</div><div class="card"><h2>Pagamentos em aberto</h2>${open.map(o=>`<div class="break-row"><span>${esc(o.customer||'Cliente')} · ${dateBR(o.date)}</span><b>${money(o.total)}</b></div>`).join('')||'<div class="empty">Nenhum pagamento pendente.</div>'}</div></div>`;}
  renderReports=function(){const body=state.tab==='productReport'?reportProduct():state.tab==='clientsReport'?reportClients():state.tab==='financeReport'?reportFinance():reportOrders();return `${pageHead('Relatórios','Pedidos, produtos, clientes e financeiro em leituras separadas.',`<button class="btn outline" onclick="exportCSV()">Exportar CSV</button>`)}${reportTabs()}${body}`;};

  // ---------- Configurações: dados do negócio + recursos do sistema ----------
  const oldSettingsBusiness=settingsBusiness;
  settingsBusiness=function(){return oldSettingsBusiness()+`<div class="card" style="margin-top:14px"><h2>Dados do negócio</h2><div class="form-grid"><label class="field span-4"><span class="label">Seu nome</span><input id="cfgOwner" value="${esc(DB.config.ownerName)}"></label><label class="field span-4"><span class="label">Telefone</span><input id="cfgPhone" value="${esc(DB.config.businessPhone)}"></label><label class="field span-4"><span class="label">E-mail</span><input id="cfgEmail" value="${esc(DB.config.businessEmail)}"></label><label class="field span-6"><span class="label">WhatsApp / link curto</span><input id="cfgWhats" value="${esc(DB.config.whatsappLink)}"></label><label class="field span-3"><span class="label">Validade orçamento (dias)</span><input id="cfgValid" value="${n(DB.config.orderValidityDays)}"></label><label class="field span-3"><span class="label">Prazo padrão (dias)</span><input id="cfgLead" value="${n(DB.config.defaultLeadDays)}"></label></div><div class="form-actions"><button class="btn primary" onclick="saveBusinessIdentity()">Salvar dados</button></div></div>`;};
  window.saveBusinessIdentity=()=>{Object.assign(DB.config,{ownerName:q('#cfgOwner').value.trim(),businessPhone:q('#cfgPhone').value.trim(),businessEmail:q('#cfgEmail').value.trim(),whatsappLink:q('#cfgWhats').value.trim(),orderValidityDays:Math.max(1,n(q('#cfgValid').value)),defaultLeadDays:Math.max(0,n(q('#cfgLead').value))});saveDB();toast('Dados do negócio salvos.');};

  // ---------- Render principal v5 ----------
  render=function(){renderNav();const v=q('#view');const map={dashboard:renderDashboard,orders:renderOrders,calendar:renderCalendar,catalog:renderCatalog,finance:renderFinance,stock:renderStock,pricing:renderPricing,reports:renderReports,records:renderRecords,settings:renderSettings};v.innerHTML=(map[state.view]||renderDashboard)();bindView();};

  // Ajustes ao navegar para views com abas próprias.
  const oldRenderNav=renderNav;
  renderNav=function(){oldRenderNav();q('#mainNav').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;if(state.view==='pricing')state.tab='calculator';if(state.view==='catalog')state.tab='overview';if(state.view==='reports')state.tab='ordersReport';if(state.view==='records')state.tab='products';closeSidebar();render();});};

  installGlobalSearch();render();
})();
